### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#1]
```
details:
  msg: It is better to keep your mouth closed and let people think you are a fool than to open it and remove all doubt - Mark Twain
id: 6b8f920b9e9b478da01003b4e1eccc17
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-enterprise-notifications:8668
  hostid: anchore-engine-anchore-engine-api-c655f5884-tvczx
  request_id: null
  servicename: notifications
timestamp: '2020-05-18T17:26:07.620971'
type: system.test.random_wisdom
```
