### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#100]
```
details:
  result:
    group: alpine:3.4
    status: success
    total_time_seconds: 14.735540390014648
    updated_image_count: 0
    updated_record_count: 678
id: abbd3ed5d9e245ccadc29291c5b6a078
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.4
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:05:44.790440Z'
type: system.feeds.sync.group_completed
```
