### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#101]
```
details: {}
id: 8753fd112a5649138f119b0daf6d5bfc
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:05:44.868539Z'
type: system.feeds.sync.group_started
```
