### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#102]
```
details:
  result:
    group: alpine:3.5
    status: success
    total_time_seconds: 18.994615077972412
    updated_image_count: 0
    updated_record_count: 875
id: e3941602db6d4b958f17567d9ff95508
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:06:03.933583Z'
type: system.feeds.sync.group_completed
```
