### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#103]
```
details: {}
id: 0a73a8f2a204472bbe26238a0726d061
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:06:04.015340Z'
type: system.feeds.sync.group_started
```
