### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#104]
```
details:
  result:
    group: alpine:3.6
    status: success
    total_time_seconds: 23.152676105499268
    updated_image_count: 0
    updated_record_count: 1049
id: 349ee0317b75400cb67969153ff38d85
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:06:27.244106Z'
type: system.feeds.sync.group_completed
```
