### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#105]
```
details: {}
id: 059880f8f408473e812d889fdc52d35a
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:06:27.318366Z'
type: system.feeds.sync.group_started
```
