### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#106]
```
details:
  result:
    group: alpine:3.7
    status: success
    total_time_seconds: 31.517827033996582
    updated_image_count: 0
    updated_record_count: 1395
id: 63157d6f90a849f0a6a6d22317072bc5
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:06:58.908843Z'
type: system.feeds.sync.group_completed
```
