### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#108]
```
details:
  result:
    group: alpine:3.8
    status: success
    total_time_seconds: 33.14385008811951
    updated_image_count: 0
    updated_record_count: 1483
id: 7d5950ffb6cd4511bc60247f6fbf291a
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:07:32.203116Z'
type: system.feeds.sync.group_completed
```
