### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#109]
```
details: {}
id: aadf5303b7bf408ba056f28e3c252ed1
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.9
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:07:32.274116Z'
type: system.feeds.sync.group_started
```
