### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#11]
```
details:
  result:
    group: msrc:11583
    status: success
    total_time_seconds: 0.07890176773071289
    updated_image_count: 0
    updated_record_count: 0
id: d0ccbbbec92f4fab87da23e8ec712140
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11583
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:14.629582Z'
type: system.feeds.sync.group_completed
```
