### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#110]
```
details:
  result:
    group: alpine:3.9
    status: success
    total_time_seconds: 34.096977949142456
    updated_image_count: 0
    updated_record_count: 1558
id: 4e6f8ef331194f79bced6e4b5afb0f39
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.9
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:08:06.442100Z'
type: system.feeds.sync.group_completed
```
