### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#111]
```
details: {}
id: 6a13d7fbcef046f08d27f2e8def9cd9b
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/amzn:2
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:08:06.522303Z'
type: system.feeds.sync.group_started
```
