### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#112]
```
details:
  result:
    group: amzn:2
    status: success
    total_time_seconds: 33.57856607437134
    updated_image_count: 0
    updated_record_count: 345
id: b4e3c762258a491a8f1c7254af6ae98f
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/amzn:2
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:08:40.171557Z'
type: system.feeds.sync.group_completed
```
