### ISSUE TITLE
[ANCHORE] Service down

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#114]
```
details:
  cause: no heartbeat from service in (300) seconds
  host_id: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  service_name: policy_engine
id: b5cd82d7b63d486fadbf697274a33094
level: error
message: Service down
resource:
  id: http://anchore-engine-anchore-engine-policy:8087
  type: service
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-catalog:8082
  hostid: anchore-engine-anchore-engine-catalog-77849fbd77-gbknh
  request_id: null
  servicename: catalog
timestamp: '2020-05-18T22:08:43.218606Z'
type: system.service.state_transition.down
```
