### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#115]
```
details:
  result:
    group: centos:5
    status: success
    total_time_seconds: 50.24862241744995
    updated_image_count: 0
    updated_record_count: 1171
id: 680f541865104e83835fcb7bab2c0f11
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/centos:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:09:30.566510Z'
type: system.feeds.sync.group_completed
```
