### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#116]
```
details: {}
id: a2bf2910a1ad4dbca5299bfe04f29015
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/centos:6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:09:30.637695Z'
type: system.feeds.sync.group_started
```
