### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#118]
```
details: {}
id: 4c48efba1da84bc280c5395e9b6a5211
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/centos:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:09:33.891449Z'
type: system.feeds.sync.group_started
```
