### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#120]
```
details: {}
id: 5ee443bb7b7d44409439119901d2f529
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/centos:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:09:37.155973Z'
type: system.feeds.sync.group_started
```
