### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#123]
```
details:
  cause: Failed to sync to db
id: 4a47876f401a4dfbb766efcdeee8cf90
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/debian:10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:09:43.577017Z'
type: system.feeds.sync.group_failed
```
