### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#124]
```
details: {}
id: 9b3b89b159ee46849469686cc5684f9f
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/debian:11
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:09:43.641936Z'
type: system.feeds.sync.group_started
```
