### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#126]
```
details: {}
id: 4a69aea23f724f7f908ea66b04db5a88
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/debian:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:09:46.873582Z'
type: system.feeds.sync.group_started
```
