### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#127]
```
details:
  cause: Failed to sync to db
id: 7211d39d30124abaa6879fc89aba47e2
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/debian:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:09:50.047095Z'
type: system.feeds.sync.group_failed
```
