### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#129]
```
details:
  cause: Failed to sync to db
id: 77cb083c448c40b1a403f4acba0e2d0d
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/debian:9
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:09:53.312684Z'
type: system.feeds.sync.group_failed
```
