### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#130]
```
details: {}
id: 54418ca4e50b44fbb78db519a8f98edf
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/debian:unstable
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:09:53.377484Z'
type: system.feeds.sync.group_started
```
