### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#132]
```
details: {}
id: 9cc2cf76b6b54e5b9b95a9a1a8ef994f
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ol:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:09:56.607479Z'
type: system.feeds.sync.group_started
```
