### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#137]
```
details:
  cause: Failed to sync to db
id: 3ff2c618980243089bde27b9d0f0372e
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/ol:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:10:06.263851Z'
type: system.feeds.sync.group_failed
```
