### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#138]
```
details: {}
id: a2c7d2d3f0da48e7a89aa6f9dd3523cc
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ol:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:10:06.331218Z'
type: system.feeds.sync.group_started
```
