### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#141]
```
details:
  cause: Failed to sync to db
id: be827d85cd9148a89cd12f855d6e960c
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/rhel:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:10:12.728887Z'
type: system.feeds.sync.group_failed
```
