### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#143]
```
details:
  cause: Failed to sync to db
id: 35d2c70be91845f4acd1d8a93220cf28
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/rhel:6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:10:15.960717Z'
type: system.feeds.sync.group_failed
```
