### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#144]
```
details: {}
id: 4442ef6fbe5b45dda9dc150d5d6fa992
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/rhel:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:10:16.129425Z'
type: system.feeds.sync.group_started
```
