### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#145]
```
details:
  cause: Failed to sync to db
id: aa577986e9334e8da475fa9f8718f3e0
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/rhel:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:10:19.290834Z'
type: system.feeds.sync.group_failed
```
