### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#146]
```
details: {}
id: d327d7761a374fd9aef0bcbf6f73d635
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/rhel:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:10:19.358034Z'
type: system.feeds.sync.group_started
```
