### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#147]
```
details:
  result:
    group: rhel:8
    status: success
    total_time_seconds: 44.12024903297424
    updated_image_count: 0
    updated_record_count: 1478
id: 39b0aec57c424d7ab27761a54bae5a31
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/rhel:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:11:03.550071Z'
type: system.feeds.sync.group_completed
```
