### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#148]
```
details: {}
id: fe8e68d0f29748c5ad99929d1f09a6c6
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:12.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:11:03.623341Z'
type: system.feeds.sync.group_started
```
