### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#149]
```
details:
  result:
    group: ubuntu:12.04
    status: success
    total_time_seconds: 279.68193912506104
    updated_image_count: 0
    updated_record_count: 14918
id: 0cba0448a20c435bb65184dafee1646b
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:12.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:15:43.377478Z'
type: system.feeds.sync.group_completed
```
