### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#151]
```
details:
  result:
    group: ubuntu:12.10
    status: success
    total_time_seconds: 102.88974452018738
    updated_image_count: 0
    updated_record_count: 5641
id: 37f23e7a0b834594be6d21c96946073e
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:12.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:17:26.417057Z'
type: system.feeds.sync.group_completed
```
