### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#152]
```
details: {}
id: fe839eb36998472f8e8e40c4343e20f3
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:13.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:17:26.490645Z'
type: system.feeds.sync.group_started
```
