### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#153]
```
details:
  result:
    group: ubuntu:13.04
    status: success
    total_time_seconds: 70.12640619277954
    updated_image_count: 0
    updated_record_count: 4117
id: b40b0b37db4a45b8835414e5b854cba0
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:13.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:18:36.697193Z'
type: system.feeds.sync.group_completed
```
