### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#154]
```
details: {}
id: 5363942e912141718accf919b14bb4d9
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:14.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:18:36.777652Z'
type: system.feeds.sync.group_started
```
