### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#155]
```
details:
  result:
    group: ubuntu:14.04
    status: success
    total_time_seconds: 381.66490626335144
    updated_image_count: 0
    updated_record_count: 21570
id: a8d8c45aa11a42e183f423cb1b4fb8d8
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:14.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:24:58.517557Z'
type: system.feeds.sync.group_completed
```
