### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#156]
```
details: {}
id: 0a831dc6d23c4e63beeac83cf59e206b
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:14.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:24:58.592644Z'
type: system.feeds.sync.group_started
```
