### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#157]
```
details:
  result:
    group: ubuntu:14.10
    status: success
    total_time_seconds: 88.6170334815979
    updated_image_count: 0
    updated_record_count: 4437
id: 732c5faffb9045648b0551e6a0992321
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:14.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:26:27.282395Z'
type: system.feeds.sync.group_completed
```
