### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#159]
```
details:
  result:
    group: ubuntu:15.04
    status: success
    total_time_seconds: 110.32844495773315
    updated_image_count: 0
    updated_record_count: 5892
id: 56d81bb27691495099133fa34b354674
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:15.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:28:17.757096Z'
type: system.feeds.sync.group_completed
```
