### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#160]
```
details: {}
id: 66146968f9f04a5e9e21a45bcf31218a
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:15.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:28:17.834993Z'
type: system.feeds.sync.group_started
```
