### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#161]
```
details:
  result:
    group: ubuntu:15.10
    status: success
    total_time_seconds: 128.57831263542175
    updated_image_count: 0
    updated_record_count: 6488
id: 5c291bf4378e4363b7e3e99de947c83d
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:15.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:30:26.489879Z'
type: system.feeds.sync.group_completed
```
