### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#162]
```
details: {}
id: d71e4f665c064ea1b4a14ef12372f7e9
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:16.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:30:26.568823Z'
type: system.feeds.sync.group_started
```
