### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#163]
```
details:
  result:
    group: ubuntu:16.04
    status: success
    total_time_seconds: 377.6212201118469
    updated_image_count: 0
    updated_record_count: 18683
id: 7796761f152e40328a220464f57bb367
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:16.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:36:44.263007Z'
type: system.feeds.sync.group_completed
```
