### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#164]
```
details: {}
id: e4ec8c326bcb47cd96f9333489aade68
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:16.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:36:44.338855Z'
type: system.feeds.sync.group_started
```
