### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#165]
```
details:
  result:
    group: ubuntu:16.10
    status: success
    total_time_seconds: 143.13877820968628
    updated_image_count: 0
    updated_record_count: 8606
id: 096324fa31f44d9dba6da79fedba8ee7
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:16.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:39:07.553065Z'
type: system.feeds.sync.group_completed
```
