### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#167]
```
details:
  result:
    group: ubuntu:17.04
    status: success
    total_time_seconds: 144.4760618209839
    updated_image_count: 0
    updated_record_count: 9094
id: 6c50e5a50d174217af6c560f17b75f38
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:17.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:41:32.168962Z'
type: system.feeds.sync.group_completed
```
