### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#168]
```
details: {}
id: 0050008fbcbe4e91b5908c03bcad3c07
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:17.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:41:32.245075Z'
type: system.feeds.sync.group_started
```
