### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#169]
```
details:
  result:
    group: ubuntu:17.10
    status: success
    total_time_seconds: 123.76042103767395
    updated_image_count: 0
    updated_record_count: 7898
id: f52c72df86394b43bafc39f722fe1531
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:17.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:43:36.088093Z'
type: system.feeds.sync.group_completed
```
