### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#17]
```
details:
  result:
    group: msrc:10789
    status: success
    total_time_seconds: 0.06816911697387695
    updated_image_count: 0
    updated_record_count: 0
id: 5498fe030db2435c99c28407308a9313
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10789
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:15.287986Z'
type: system.feeds.sync.group_completed
```
