### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#170]
```
details: {}
id: ac00ceffb42b4355999a9b2fa9191ca1
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:18.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:43:36.156626Z'
type: system.feeds.sync.group_started
```
