### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#171]
```
details:
  result:
    group: ubuntu:18.04
    status: success
    total_time_seconds: 244.534996509552
    updated_image_count: 0
    updated_record_count: 12951
id: 3b9baa4406444de591413717402254c7
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:18.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:47:40.760503Z'
type: system.feeds.sync.group_completed
```
