### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#175]
```
details:
  cause: Failed to sync to db
id: b0e918809e384721aa6e360b9c2aa265
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/ubuntu:19.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:47:47.223756Z'
type: system.feeds.sync.group_failed
```
