### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#176]
```
details: {}
id: 30955582d6644157a1c003050065c4c9
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:19.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:47:47.298096Z'
type: system.feeds.sync.group_started
```
