### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#177]
```
details:
  cause: Failed to sync to db
id: 39d0bb6591a34be3ba6a15f9a7d3c6ba
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/ubuntu:19.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:47:50.459391Z'
type: system.feeds.sync.group_failed
```
