### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#178]
```
details: {}
id: 33c93efa6a854a3d809be9dd631f7bfd
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:20.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:47:50.528223Z'
type: system.feeds.sync.group_started
```
