### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#179]
```
details:
  cause: Failed to sync to db
id: adfbad8538764953ab504028fbd015b5
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/ubuntu:20.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:47:53.692076Z'
type: system.feeds.sync.group_failed
```
