### ISSUE TITLE
[ANCHORE] Feed sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#180]
```
details:
  cause: One or more groups failed to sync
id: 9edd126711344f5086e3f7283f0bcfce
level: error
message: Feed sync failed
resource:
  id: vulnerabilities
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:47:53.764028Z'
type: system.feeds.sync.feed_failed
```
