### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#181]
```
details: {}
id: b528f7c94f614d36b4979407b01acf5c
level: info
message: Feed sync started
resource:
  id: vulndb
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:47:53.832322Z'
type: system.feeds.sync.feed_started
```
