### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#182]
```
details: {}
id: 3ec28b83104e4d54a645bd448252913f
level: info
message: Feed group sync started
resource:
  id: vulndb/vulndb:vulnerabilities
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:47:54.031080Z'
type: system.feeds.sync.group_started
```
