### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#183]
```
details:
  cause: Failed to sync to db
id: d2e9772e3a41400dbc85bc2981c87c20
level: error
message: Feed group sync failed
resource:
  id: vulndb/vulndb:vulnerabilities
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:47:57.211112Z'
type: system.feeds.sync.group_failed
```
