### ISSUE TITLE
[ANCHORE] Feed sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#184]
```
details:
  cause: One or more groups failed to sync
id: d138272c93dd40a7894d66cbee8fd2c3
level: error
message: Feed sync failed
resource:
  id: vulndb
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:47:57.273040Z'
type: system.feeds.sync.feed_failed
```
