### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#186]
```
details: {}
id: 1fb52c8d389f4c0185c59ce34aef8eea
level: info
message: Feed group sync started
resource:
  id: nvdv2/nvdv2:cves
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:47:57.528574Z'
type: system.feeds.sync.group_started
```
