### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#187]
```
details:
  cause: Failed to sync to db
id: ab068f0af8404205a36fb001bcca8fe7
level: error
message: Feed group sync failed
resource:
  id: nvdv2/nvdv2:cves
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:00.703733Z'
type: system.feeds.sync.group_failed
```
