### ISSUE TITLE
[ANCHORE] Feed sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#188]
```
details:
  cause: One or more groups failed to sync
id: 005814f898dc44308c2536931942bc1a
level: error
message: Feed sync failed
resource:
  id: nvdv2
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:00.770014Z'
type: system.feeds.sync.feed_failed
```
