### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#19]
```
details:
  result:
    group: msrc:11498
    status: success
    total_time_seconds: 0.07366776466369629
    updated_image_count: 0
    updated_record_count: 0
id: ecc151d7acce41ea9b423a34b4a980dd
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11498
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:15.506700Z'
type: system.feeds.sync.group_completed
```
