### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#191]
```
details:
  result:
    group: msrc:11466
    status: success
    total_time_seconds: 1.2317054271697998
    updated_image_count: 0
    updated_record_count: 0
id: 4b57c246e6c94945adbf36e25c802230
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11466
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:02.334389Z'
type: system.feeds.sync.group_completed
```
