### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#193]
```
details:
  result:
    group: msrc:11646
    status: success
    total_time_seconds: 0.11182498931884766
    updated_image_count: 0
    updated_record_count: 0
id: afec6764cbb14d55ba65c297db59a84d
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11646
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:02.587169Z'
type: system.feeds.sync.group_completed
```
