### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#194]
```
details: {}
id: 00ed8ca8e83f42c1b1613f3d54ba342b
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10789
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:02.646832Z'
type: system.feeds.sync.group_started
```
