### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#195]
```
details:
  result:
    group: msrc:10789
    status: success
    total_time_seconds: 0.11808061599731445
    updated_image_count: 0
    updated_record_count: 0
id: c9ab6b22cdda4cdc9f8f72700a6d9eb9
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10789
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:02.839443Z'
type: system.feeds.sync.group_completed
```
