### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#197]
```
details:
  result:
    group: msrc:11644
    status: success
    total_time_seconds: 0.12064170837402344
    updated_image_count: 0
    updated_record_count: 0
id: af3f6e853af14b94a76a5d8a191f45bb
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11644
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:03.091821Z'
type: system.feeds.sync.group_completed
```
