### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#199]
```
details:
  result:
    group: msrc:11713
    status: success
    total_time_seconds: 0.11301064491271973
    updated_image_count: 0
    updated_record_count: 0
id: b9d8290497d54936be99d69e5b509e63
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11713
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:03.342886Z'
type: system.feeds.sync.group_completed
```
