### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#20]
```
details: {}
id: 91dfad27124f4dab889950003e78ed72
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11568
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:15.571308Z'
type: system.feeds.sync.group_started
```
