### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#201]
```
details:
  result:
    group: msrc:11645
    status: success
    total_time_seconds: 0.1185610294342041
    updated_image_count: 0
    updated_record_count: 0
id: 349e9ab63de24c4b974c1a66154e4700
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11645
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:03.599167Z'
type: system.feeds.sync.group_completed
```
