### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#202]
```
details: {}
id: 9c83073592924c1baff52d658010a79c
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11647
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:03.660324Z'
type: system.feeds.sync.group_started
```
