### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#203]
```
details:
  result:
    group: msrc:11647
    status: success
    total_time_seconds: 0.12823224067687988
    updated_image_count: 0
    updated_record_count: 0
id: e888fe9d8fd14309a511368fbe3b0be9
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11647
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:03.862858Z'
type: system.feeds.sync.group_completed
```
