### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#204]
```
details: {}
id: 32c418a9a6ab429fbbc3b23e6803bc89
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:products
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:03.926023Z'
type: system.feeds.sync.group_started
```
