### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#205]
```
details:
  result:
    group: msrc:products
    status: success
    total_time_seconds: 0.06568765640258789
    updated_image_count: 0
    updated_record_count: 0
id: d0908b377b36403b901807414a3ddb30
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:products
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:04.079423Z'
type: system.feeds.sync.group_completed
```
