### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#208]
```
details: {}
id: e5f8cd1a718b48cb852b67bb1752c7c5
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11715
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:04.423770Z'
type: system.feeds.sync.group_started
```
