### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#209]
```
details:
  result:
    group: msrc:11715
    status: success
    total_time_seconds: 0.17151808738708496
    updated_image_count: 0
    updated_record_count: 0
id: 4ddced9a8ff24338b2fe3e377a35626e
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11715
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:04.674257Z'
type: system.feeds.sync.group_completed
```
