### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#211]
```
details:
  result:
    group: msrc:11572
    status: success
    total_time_seconds: 0.12963461875915527
    updated_image_count: 0
    updated_record_count: 0
id: ba6dc25624b342a1867f779189efb46c
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11572
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:04.939696Z'
type: system.feeds.sync.group_completed
```
