### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#212]
```
details: {}
id: c1c7fb57fc2d4edc87a43654ddc34b24
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10543
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:05.006850Z'
type: system.feeds.sync.group_started
```
