### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#213]
```
details:
  result:
    group: msrc:10543
    status: success
    total_time_seconds: 0.12911128997802734
    updated_image_count: 0
    updated_record_count: 0
id: fa10c64549714316912522b93b8d319a
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10543
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:05.212168Z'
type: system.feeds.sync.group_completed
```
