### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#217]
```
details:
  result:
    group: msrc:10735
    status: success
    total_time_seconds: 0.13535761833190918
    updated_image_count: 0
    updated_record_count: 0
id: 484aaeea6694415d92d0f8daa7014edf
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10735
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:05.793709Z'
type: system.feeds.sync.group_completed
```
