### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#219]
```
details:
  result:
    group: msrc:11563
    status: success
    total_time_seconds: 0.17775416374206543
    updated_image_count: 0
    updated_record_count: 0
id: 12a52992f835400580280159ea2ab948
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11563
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:06.147072Z'
type: system.feeds.sync.group_completed
```
