### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#220]
```
details: {}
id: 33fdbe0362864152a09f9e999781ce77
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10853
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:06.209614Z'
type: system.feeds.sync.group_started
```
