### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#223]
```
details:
  result:
    group: msrc:11714
    status: success
    total_time_seconds: 0.12632274627685547
    updated_image_count: 0
    updated_record_count: 0
id: 2b68ee293c9d4404b53d2d105e53b4c0
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11714
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:06.676780Z'
type: system.feeds.sync.group_completed
```
