### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#224]
```
details: {}
id: 09ef777f294c4571877088d4125033ed
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10379
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:06.744763Z'
type: system.feeds.sync.group_started
```
