### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#225]
```
details:
  result:
    group: msrc:10379
    status: success
    total_time_seconds: 0.11965632438659668
    updated_image_count: 0
    updated_record_count: 0
id: af235fc401574b5db63afd6c1529f2b8
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10379
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:06.936395Z'
type: system.feeds.sync.group_completed
```
