### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#228]
```
details: {}
id: dbf6b8f76b894a6c8ac96d9a723cef6d
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10816
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:07.290220Z'
type: system.feeds.sync.group_started
```
