### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#229]
```
details:
  result:
    group: msrc:10816
    status: success
    total_time_seconds: 0.11612939834594727
    updated_image_count: 0
    updated_record_count: 0
id: f74bc6b51d2743d8bf4af0a549da8541
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10816
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:07.478513Z'
type: system.feeds.sync.group_completed
```
