### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#23]
```
details:
  result:
    group: msrc:11570
    status: success
    total_time_seconds: 0.06929707527160645
    updated_image_count: 0
    updated_record_count: 0
id: 7198dfd9e7a54db7bbf574e4bc0087ae
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11570
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:15.942322Z'
type: system.feeds.sync.group_completed
```
