### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#231]
```
details:
  result:
    group: msrc:10952
    status: success
    total_time_seconds: 0.11387848854064941
    updated_image_count: 0
    updated_record_count: 0
id: 0737068850d343bd92ba1234af8ba0f5
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10952
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:07.731858Z'
type: system.feeds.sync.group_completed
```
