### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#232]
```
details: {}
id: c4696a62f74c438fa08f5f0eb005e0b3
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11569
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:07.793634Z'
type: system.feeds.sync.group_started
```
