### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#233]
```
details:
  result:
    group: msrc:11569
    status: success
    total_time_seconds: 0.11407709121704102
    updated_image_count: 0
    updated_record_count: 0
id: 70c633c9d28747d6a1a124c992d537a4
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11569
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:07.985173Z'
type: system.feeds.sync.group_completed
```
