### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#234]
```
details: {}
id: 8af14d9ac74b42e6889a0102829ff0f6
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11712
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:08.043084Z'
type: system.feeds.sync.group_started
```
