### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#235]
```
details:
  result:
    group: msrc:11712
    status: success
    total_time_seconds: 0.11871933937072754
    updated_image_count: 0
    updated_record_count: 0
id: c7ac43185fad4f019693bdb456612654
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11712
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:08.248923Z'
type: system.feeds.sync.group_completed
```
