### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#236]
```
details: {}
id: 53ed21956e75480cb9da250f541ccb9f
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11571
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:08.314928Z'
type: system.feeds.sync.group_started
```
