### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#237]
```
details:
  result:
    group: msrc:11571
    status: success
    total_time_seconds: 0.12176179885864258
    updated_image_count: 0
    updated_record_count: 0
id: ff2a403f3eff4c659e135e967dd5988d
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11571
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:08.510646Z'
type: system.feeds.sync.group_completed
```
