### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#239]
```
details:
  result:
    group: msrc:10852
    status: success
    total_time_seconds: 0.1191720962524414
    updated_image_count: 0
    updated_record_count: 0
id: a86dc6248aec46f590d8ecb50ffb977f
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10852
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:08.776649Z'
type: system.feeds.sync.group_completed
```
