### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#241]
```
details:
  result:
    group: msrc:11454
    status: success
    total_time_seconds: 0.12282896041870117
    updated_image_count: 0
    updated_record_count: 0
id: 48bc9201e37544c5a37298f1cef1a147
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11454
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:09.042343Z'
type: system.feeds.sync.group_completed
```
