### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#243]
```
details:
  result:
    group: msrc:11453
    status: success
    total_time_seconds: 0.11672568321228027
    updated_image_count: 0
    updated_record_count: 0
id: 03411a8969e54073950fdf0c734c4c6a
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11453
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:09.297957Z'
type: system.feeds.sync.group_completed
```
