### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#245]
```
details:
  result:
    group: msrc:10855
    status: success
    total_time_seconds: 0.18057632446289062
    updated_image_count: 0
    updated_record_count: 0
id: 957398f0dccb454f811b4a5f6ef39b36
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10855
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:09.636649Z'
type: system.feeds.sync.group_completed
```
