### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#246]
```
details: {}
id: 2396893082ae498da44cdfea93738c82
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10788
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:09.703039Z'
type: system.feeds.sync.group_started
```
