### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#249]
```
details:
  result:
    group: msrc:11499
    status: success
    total_time_seconds: 0.12072253227233887
    updated_image_count: 0
    updated_record_count: 0
id: a4cfeeab43df41c2a221492b2e686c2f
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11499
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:10.197241Z'
type: system.feeds.sync.group_completed
```
