### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#25]
```
details:
  result:
    group: msrc:11644
    status: success
    total_time_seconds: 0.07960867881774902
    updated_image_count: 0
    updated_record_count: 0
id: 6da96bb303ed43ceb02005773d471b12
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11644
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:16.168747Z'
type: system.feeds.sync.group_completed
```
