### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#251]
```
details:
  result:
    group: msrc:11498
    status: success
    total_time_seconds: 0.13338470458984375
    updated_image_count: 0
    updated_record_count: 0
id: 8d8258ed48024fd292a8c39b5043bb4c
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11498
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:10.475416Z'
type: system.feeds.sync.group_completed
```
