### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#253]
```
details:
  result:
    group: msrc:11568
    status: success
    total_time_seconds: 0.12323570251464844
    updated_image_count: 0
    updated_record_count: 0
id: c2fc59ec30a94d83b532ab804cb19f14
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11568
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:10.745484Z'
type: system.feeds.sync.group_completed
```
