### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#255]
```
details:
  result:
    group: msrc:11570
    status: success
    total_time_seconds: 0.18084406852722168
    updated_image_count: 0
    updated_record_count: 0
id: 06173768fd4a4c0ea5b76bdd104267c2
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11570
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:11.081938Z'
type: system.feeds.sync.group_completed
```
