### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#257]
```
details:
  result:
    group: msrc:11583
    status: success
    total_time_seconds: 0.1641223430633545
    updated_image_count: 0
    updated_record_count: 0
id: 924cb17de6844cbaa7e87a10d8107de5
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11583
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:11.399231Z'
type: system.feeds.sync.group_completed
```
