### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#261]
```
details:
  result:
    group: github:composer
    status: success
    total_time_seconds: 0.08265161514282227
    updated_image_count: 0
    updated_record_count: 0
id: fc1522fa505c446ba559db739fa836cf
level: info
message: Feed group sync completed
resource:
  id: github/github:composer
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:11.883107Z'
type: system.feeds.sync.group_completed
```
