### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#262]
```
details: {}
id: 64b6e2129d1e4371ae8b8dec7fc719b5
level: info
message: Feed group sync started
resource:
  id: github/github:gem
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:11.963535Z'
type: system.feeds.sync.group_started
```
