### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#263]
```
details:
  result:
    group: github:gem
    status: success
    total_time_seconds: 0.13936281204223633
    updated_image_count: 0
    updated_record_count: 0
id: 332878fe3bc5491ab593fb3bba9afde5
level: info
message: Feed group sync completed
resource:
  id: github/github:gem
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:12.196635Z'
type: system.feeds.sync.group_completed
```
