### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#265]
```
details:
  result:
    group: github:npm
    status: success
    total_time_seconds: 0.11978650093078613
    updated_image_count: 0
    updated_record_count: 0
id: 4fb066b59de14dfd9e44862343a5257a
level: info
message: Feed group sync completed
resource:
  id: github/github:npm
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:12.476275Z'
type: system.feeds.sync.group_completed
```
