### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#266]
```
details: {}
id: b7078ea2a64545b58fc9ac3c2ecbd28a
level: info
message: Feed group sync started
resource:
  id: github/github:nuget
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:12.546234Z'
type: system.feeds.sync.group_started
```
