### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#267]
```
details:
  result:
    group: github:nuget
    status: success
    total_time_seconds: 0.07560324668884277
    updated_image_count: 0
    updated_record_count: 0
id: 02e0108ceaa8417d845c95511cb0747b
level: info
message: Feed group sync completed
resource:
  id: github/github:nuget
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:12.704005Z'
type: system.feeds.sync.group_completed
```
