### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#268]
```
details: {}
id: c42cecd525874f4295b3153bdb7785ae
level: info
message: Feed group sync started
resource:
  id: github/github:python
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:12.761096Z'
type: system.feeds.sync.group_started
```
