### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#269]
```
details:
  result:
    group: github:python
    status: success
    total_time_seconds: 0.11715054512023926
    updated_image_count: 0
    updated_record_count: 0
id: 3ccd4f67018d44aab80ad61a702740b8
level: info
message: Feed group sync completed
resource:
  id: github/github:python
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:12.952144Z'
type: system.feeds.sync.group_completed
```
