### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#27]
```
details:
  result:
    group: msrc:11713
    status: success
    total_time_seconds: 0.06216764450073242
    updated_image_count: 0
    updated_record_count: 0
id: 57b2457d5487431db6b77a741e5f869f
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11713
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:16.389776Z'
type: system.feeds.sync.group_completed
```
