### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#271]
```
details:
  result:
    group: github:java
    status: success
    total_time_seconds: 0.12036323547363281
    updated_image_count: 0
    updated_record_count: 0
id: 7561a556edac470899b3e8a519ef0901
level: info
message: Feed group sync completed
resource:
  id: github/github:java
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:13.214883Z'
type: system.feeds.sync.group_completed
```
