### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#274]
```
details: {}
id: 11e4b5a654304b4694ec6ba911744880
level: info
message: Feed group sync started
resource:
  id: packages/gem
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:48:13.545964Z'
type: system.feeds.sync.group_started
```
