### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#275]
```
details:
  result:
    group: gem
    status: success
    total_time_seconds: 549.2436912059784
    updated_image_count: 0
    updated_record_count: 171169
id: 6ef4710d96a8490582bddb2bfd2d8c61
level: info
message: Feed group sync completed
resource:
  id: packages/gem
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:57:22.872292Z'
type: system.feeds.sync.group_completed
```
