### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#276]
```
details: {}
id: 9b849aa0f639478a985b03480379a0e6
level: info
message: Feed group sync started
resource:
  id: packages/npm
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:57:22.961040Z'
type: system.feeds.sync.group_started
```
