### ISSUE TITLE
[ANCHORE] Service orphaned

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#277]
```
details:
  cause: no heartbeat from service in (3600) seconds
  host_id: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  service_name: policy_engine
id: d2936e9d78174310b2eb49cb1e5f61b1
level: error
message: Service orphaned
resource:
  id: http://anchore-engine-anchore-engine-policy:8087
  type: service
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-catalog:8082
  hostid: anchore-engine-anchore-engine-catalog-77849fbd77-gbknh
  request_id: null
  servicename: catalog
timestamp: '2020-05-18T23:03:53.002873Z'
type: system.service.state_transition.orphaned
```
