### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#278]
```
details:
  result:
    group: npm
    status: success
    total_time_seconds: 4188.3944211006165
    updated_image_count: 0
    updated_record_count: 907000
id: 36163e44b0fe4d7a83bdf4304888dfe8
level: info
message: Feed group sync completed
resource:
  id: packages/npm
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T00:07:11.436414Z'
type: system.feeds.sync.group_completed
```
