### ISSUE TITLE
[ANCHORE] Feed sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#279]
```
details: {}
id: a26c20caceed4234a6032bd3f7987d5d
level: info
message: Feed sync completed
resource:
  id: packages
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T00:07:11.603119Z'
type: system.feeds.sync.feed_completed
```
