### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#28]
```
details: {}
id: c2023ebee8854db38b6b3a479dc19db3
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11645
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:16.459509Z'
type: system.feeds.sync.group_started
```
