### ISSUE TITLE
[ANCHORE] Feeds sync task completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#280]
```
details:
  sync_feed_types:
  - vulnerabilities
  - packages
  - nvdv2
  - vulndb
  - microsoft
  - github
id: 18146e23f63b4adb8f30362be81ca936
level: info
message: Feeds sync task completed
resource:
  id: null
  type: feeds
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T00:07:11.668914Z'
type: system.feeds.sync.completed
```
