### ISSUE TITLE
[ANCHORE] Feeds sync task started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#281]
```
details:
  sync_feed_types:
  - vulnerabilities
  - packages
  - nvdv2
  - vulndb
  - microsoft
  - github
id: 39a4151130c14566a2a119724b4699f8
level: info
message: Feeds sync task started
resource:
  id: null
  type: feeds
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:07:11.927450Z'
type: system.feeds.sync.started
```
