### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#282]
```
details: {}
id: 8ba999269fd34f4799ed61a58f4b4389
level: info
message: Feed sync started
resource:
  id: vulnerabilities
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:07:12.196489Z'
type: system.feeds.sync.feed_started
```
