### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#284]
```
details:
  result:
    group: alpine:3.10
    status: success
    total_time_seconds: 0.29648828506469727
    updated_image_count: 0
    updated_record_count: 0
id: a1bd4ca54bee4b0ba2ef50dde9aeab2d
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:07:12.628146Z'
type: system.feeds.sync.group_completed
```
