### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#285]
```
details: {}
id: 5e1cf8a32d2f4dc6a4d303cea488d5fa
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.11
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:07:12.695504Z'
type: system.feeds.sync.group_started
```
