### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#286]
```
details:
  result:
    group: alpine:3.11
    status: success
    total_time_seconds: 0.12368631362915039
    updated_image_count: 0
    updated_record_count: 0
id: 3d484af679dc47a2902767079216bd37
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.11
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:07:12.905622Z'
type: system.feeds.sync.group_completed
```
