### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#287]
```
details: {}
id: 2123ae5edd5b43a8aff772e41a0a624d
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.4
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:07:12.974266Z'
type: system.feeds.sync.group_started
```
