### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#288]
```
details:
  result:
    group: alpine:3.4
    status: success
    total_time_seconds: 0.12363648414611816
    updated_image_count: 0
    updated_record_count: 0
id: a3f80a26cf9a4f8a998f4abbf0dec3b7
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.4
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:07:13.177744Z'
type: system.feeds.sync.group_completed
```
