### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#289]
```
details: {}
id: 93874f4f741647f5a697d2822bfde1bd
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.3
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:07:13.244183Z'
type: system.feeds.sync.group_started
```
