### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#29]
```
details:
  result:
    group: msrc:11645
    status: success
    total_time_seconds: 0.07410407066345215
    updated_image_count: 0
    updated_record_count: 0
id: 9f5c33fa2d75471a8f1ccb65fff68338
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11645
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:16.619896Z'
type: system.feeds.sync.group_completed
```
