### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#290]
```
details:
  result:
    group: alpine:3.3
    status: success
    total_time_seconds: 0.1275489330291748
    updated_image_count: 0
    updated_record_count: 0
id: 6e3357f6b6094cea92d2a3edeb6773e3
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.3
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:07:13.466840Z'
type: system.feeds.sync.group_completed
```
