### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#292]
```
details:
  result:
    group: alpine:3.5
    status: success
    total_time_seconds: 0.12653136253356934
    updated_image_count: 0
    updated_record_count: 0
id: d16d74a6aacd4993a257e30a9c1ed772
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:07:13.730066Z'
type: system.feeds.sync.group_completed
```
