### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#294]
```
details:
  result:
    group: centos:6
    status: success
    total_time_seconds: 56.33531665802002
    updated_image_count: 0
    updated_record_count: 1221
id: 52dae30ef7644d3099230ed0058d009d
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/centos:6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:10.199171Z'
type: system.feeds.sync.group_completed
```
