### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#295]
```
details: {}
id: f0aeb13892ad4604bb112f22aba49ca6
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/centos:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:10.274496Z'
type: system.feeds.sync.group_started
```
