### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#299]
```
details: {}
id: 39f7a1c576f4466f8deaa7cb15b5dafe
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/debian:10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:16.777254Z'
type: system.feeds.sync.group_started
```
