### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#3]
```
details:
  msg: Never give a sword to a man who can't dance - Confucius
id: d53fbd2d3a3340309cea629ce5fc92f1
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-enterprise-notifications:8668
  hostid: anchore-engine-anchore-engine-api-c655f5884-tvczx
  request_id: null
  servicename: notifications
timestamp: '2020-05-18T17:31:19.738451'
type: system.test.random_wisdom
```
