### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#301]
```
details: {}
id: 51183c379f784a50a4287feca6c30548
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/debian:11
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:20.026306Z'
type: system.feeds.sync.group_started
```
