### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#304]
```
details:
  cause: Failed to sync to db
id: 0275471f6cac430eb9b5fc88bca73782
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/debian:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:26.458808Z'
type: system.feeds.sync.group_failed
```
