### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#305]
```
details: {}
id: cbec7dbdecb54896ae9028c9786d31df
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/debian:9
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:26.526567Z'
type: system.feeds.sync.group_started
```
