### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#307]
```
details: {}
id: 4a052415e3ea42c6900b938679cbbb62
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/debian:unstable
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:29.779908Z'
type: system.feeds.sync.group_started
```
