### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#31]
```
details:
  result:
    group: msrc:11647
    status: success
    total_time_seconds: 0.0831613540649414
    updated_image_count: 0
    updated_record_count: 0
id: 11bd533123274c9faf335b7c5fbcd1e7
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11647
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:16.903380Z'
type: system.feeds.sync.group_completed
```
