### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#312]
```
details:
  cause: Failed to sync to db
id: a7cfd31480cd4a7f9601af635c8f0021
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/ol:6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:39.548049Z'
type: system.feeds.sync.group_failed
```
