### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#314]
```
details:
  cause: Failed to sync to db
id: 2c986b1fab544bd391e2657180b47a9c
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/ol:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:42.776273Z'
type: system.feeds.sync.group_failed
```
