### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#315]
```
details: {}
id: 57de4d3e0a07410fa654eca7ad819fda
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ol:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:42.853388Z'
type: system.feeds.sync.group_started
```
