### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#316]
```
details:
  cause: Failed to sync to db
id: 86175c99b2db48f8b2dbff1922cde9cd
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/ol:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:46.045932Z'
type: system.feeds.sync.group_failed
```
