### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#317]
```
details: {}
id: a1c6722a264748ba954e9f2e297c69b2
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/rhel:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:46.108209Z'
type: system.feeds.sync.group_started
```
