### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#321]
```
details: {}
id: 71ca534d3a4d46bdb8858686ccb76023
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/rhel:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:52.565643Z'
type: system.feeds.sync.group_started
```
