### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#322]
```
details:
  cause: Failed to sync to db
id: 61b30a786aee4a269ee0ce2da28ba633
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/rhel:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:55.745924Z'
type: system.feeds.sync.group_failed
```
