### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#323]
```
details: {}
id: 6cb934c9b2b14aacb0610d34283ac265
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:18.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:55.825900Z'
type: system.feeds.sync.group_started
```
