### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#324]
```
details:
  cause: Failed to sync to db
id: 4e95591223a1423bae88c9bd8ff9a91a
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/ubuntu:18.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:59.001916Z'
type: system.feeds.sync.group_failed
```
