### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#325]
```
details: {}
id: 95a0f6c95add43c5b0c1a6a7ce362eed
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:19.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:08:59.065548Z'
type: system.feeds.sync.group_started
```
