### ISSUE TITLE
[ANCHORE] Feed group sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#326]
```
details:
  cause: Failed to sync to db
id: ff0e11fe1f91482aa00d1ab3c3f176c6
level: error
message: Feed group sync failed
resource:
  id: vulnerabilities/ubuntu:19.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:02.231842Z'
type: system.feeds.sync.group_failed
```
