### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#327]
```
details: {}
id: 5a8c09d84918494794c877cf345a4351
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:19.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:02.298105Z'
type: system.feeds.sync.group_started
```
