### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#329]
```
details: {}
id: 107b81a863d24cf8800bfe47f5360014
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:20.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:05.566638Z'
type: system.feeds.sync.group_started
```
