### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#33]
```
details:
  result:
    group: msrc:products
    status: success
    total_time_seconds: 0.06369924545288086
    updated_image_count: 0
    updated_record_count: 0
id: 6ebf98fbd2584d359658a251f2ca9bb1
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:products
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:17.115322Z'
type: system.feeds.sync.group_completed
```
