### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#332]
```
details:
  result:
    group: alpine:3.7
    status: success
    total_time_seconds: 3.305373430252075
    updated_image_count: 0
    updated_record_count: 0
id: 097b3eed18664b439122a4faa07be928
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:12.180941Z'
type: system.feeds.sync.group_completed
```
