### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#334]
```
details:
  result:
    group: ubuntu:18.04
    status: success
    total_time_seconds: 0.6647701263427734
    updated_image_count: 0
    updated_record_count: 4
id: f1abb9bd88fb462ab97e2d5728d1af69
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:18.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:12.990795Z'
type: system.feeds.sync.group_completed
```
