### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#335]
```
details: {}
id: 8b9db9e12a454c39aed10e35029b9f51
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/rhel:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:13.049467Z'
type: system.feeds.sync.group_started
```
