### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#336]
```
details:
  result:
    group: rhel:8
    status: success
    total_time_seconds: 0.13521194458007812
    updated_image_count: 0
    updated_record_count: 0
id: 2da643f0c2b741eebd30d8a4aacfaa69
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/rhel:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:13.262563Z'
type: system.feeds.sync.group_completed
```
