### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#338]
```
details:
  result:
    group: alpine:3.6
    status: success
    total_time_seconds: 0.13799571990966797
    updated_image_count: 0
    updated_record_count: 0
id: e5f61364a4264534859ba3f8c9c26f38
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:13.534287Z'
type: system.feeds.sync.group_completed
```
