### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#339]
```
details: {}
id: 7f2d114ee2844c81b8e7ed73c6a18876
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:13.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:13.593415Z'
type: system.feeds.sync.group_started
```
