### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#34]
```
details: {}
id: 2a3e737c45af428fbb328dee8f1f1cd7
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10951
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:17.185740Z'
type: system.feeds.sync.group_started
```
