### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#341]
```
details: {}
id: fbfe344b8ea34a4a8563898963fc5de0
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:13.889470Z'
type: system.feeds.sync.group_started
```
