### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#342]
```
details:
  result:
    group: alpine:3.8
    status: success
    total_time_seconds: 0.1394355297088623
    updated_image_count: 0
    updated_record_count: 0
id: dd994b9ed226445f8622afbd4b6b0cc6
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:14.103579Z'
type: system.feeds.sync.group_completed
```
