### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#343]
```
details: {}
id: ca52c94b104348e096b82ffa8a7500c0
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.9
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:14.170126Z'
type: system.feeds.sync.group_started
```
