### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#344]
```
details:
  result:
    group: alpine:3.9
    status: success
    total_time_seconds: 0.13982701301574707
    updated_image_count: 0
    updated_record_count: 0
id: 843bef917ba2433fa390b53e1130b726
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.9
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:14.389002Z'
type: system.feeds.sync.group_completed
```
