### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#346]
```
details:
  result:
    group: centos:5
    status: success
    total_time_seconds: 0.17663812637329102
    updated_image_count: 0
    updated_record_count: 0
id: d81f0a9b8ae34faf822d560236b2e21e
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/centos:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:14.708458Z'
type: system.feeds.sync.group_completed
```
