### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#349]
```
details: {}
id: 57666a0bc5c74d288ff666fba94e677b
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/amzn:2
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:15.220205Z'
type: system.feeds.sync.group_started
```
