### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#35]
```
details:
  result:
    group: msrc:10951
    status: success
    total_time_seconds: 0.07243657112121582
    updated_image_count: 0
    updated_record_count: 0
id: 91bd24caf6d64abdb60b4b02459bcf2f
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10951
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:17.331911Z'
type: system.feeds.sync.group_completed
```
