### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#350]
```
details:
  result:
    group: amzn:2
    status: success
    total_time_seconds: 0.13676810264587402
    updated_image_count: 0
    updated_record_count: 0
id: 0894dc4837bc4706a82939242ac7c005
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/amzn:2
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:15.429697Z'
type: system.feeds.sync.group_completed
```
