### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#353]
```
details: {}
id: eb8a7c6d571143629f76afa8b7cf4afb
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:12.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:15.807003Z'
type: system.feeds.sync.group_started
```
