### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#354]
```
details:
  result:
    group: ubuntu:12.10
    status: success
    total_time_seconds: 0.22290825843811035
    updated_image_count: 0
    updated_record_count: 0
id: 1c967132dfd343d8b407091cc78bab47
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:12.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:16.113752Z'
type: system.feeds.sync.group_completed
```
