### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#355]
```
details: {}
id: c2fcce68b8b4494bacb93ceb7b909ebf
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:14.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:16.185694Z'
type: system.feeds.sync.group_started
```
