### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#356]
```
details:
  result:
    group: ubuntu:14.10
    status: success
    total_time_seconds: 0.15101838111877441
    updated_image_count: 0
    updated_record_count: 0
id: 594e6b72b5414a6b81bf5de05cf90588
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:14.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:16.416167Z'
type: system.feeds.sync.group_completed
```
