### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#358]
```
details:
  result:
    group: ubuntu:16.04
    status: success
    total_time_seconds: 0.9551301002502441
    updated_image_count: 0
    updated_record_count: 9
id: 07689525efa44b29b06f70403c727ca1
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:16.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:17.511261Z'
type: system.feeds.sync.group_completed
```
