### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#359]
```
details: {}
id: 4266ff1c03f341e48becb3d68c326ad2
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:14.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:17.582877Z'
type: system.feeds.sync.group_started
```
