### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#362]
```
details:
  result:
    group: ubuntu:15.10
    status: success
    total_time_seconds: 0.1519777774810791
    updated_image_count: 0
    updated_record_count: 0
id: c6f77d017bcd4a74a81fbf8290ff2b87
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:15.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:18.143841Z'
type: system.feeds.sync.group_completed
```
