### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#363]
```
details: {}
id: dc48ef61c8dd4d46aa2d118d28f6088a
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:15.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:18.207706Z'
type: system.feeds.sync.group_started
```
