### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#364]
```
details:
  result:
    group: ubuntu:15.04
    status: success
    total_time_seconds: 0.17162442207336426
    updated_image_count: 0
    updated_record_count: 0
id: 1c9b7cdcfed941d093ad1e2e2ea466f0
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:15.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:18.454150Z'
type: system.feeds.sync.group_completed
```
