### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#366]
```
details:
  result:
    group: ubuntu:17.04
    status: success
    total_time_seconds: 0.1539313793182373
    updated_image_count: 0
    updated_record_count: 0
id: 3088846e1a0a4c3bb104f8f8da7abc84
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:17.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:18.757803Z'
type: system.feeds.sync.group_completed
```
