### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#367]
```
details: {}
id: 22fb25c83f064f23a71792d66a4058e8
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:17.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:18.818312Z'
type: system.feeds.sync.group_started
```
