### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#368]
```
details:
  result:
    group: ubuntu:17.10
    status: success
    total_time_seconds: 0.1535475254058838
    updated_image_count: 0
    updated_record_count: 0
id: 919bf2e9bb8c4659b69f67fd9f1394ff
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:17.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:19.045023Z'
type: system.feeds.sync.group_completed
```
