### ISSUE TITLE
[ANCHORE] Feed sync failed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#369]
```
details:
  cause: One or more groups failed to sync
id: 2baba74fa66d4955af7a18b6632266a5
level: error
message: Feed sync failed
resource:
  id: vulnerabilities
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:19.118041Z'
type: system.feeds.sync.feed_failed
```
