### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#37]
```
details:
  result:
    group: msrc:11715
    status: success
    total_time_seconds: 0.06317949295043945
    updated_image_count: 0
    updated_record_count: 0
id: 3a9ee08725a147a5a1d924a9f8c8bd42
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11715
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:17.548090Z'
type: system.feeds.sync.group_completed
```
