### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#371]
```
details: {}
id: 3a959aa8ba884d6b91b1f8a19ca990ac
level: info
message: Feed group sync started
resource:
  id: vulndb/vulndb:vulnerabilities
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T04:09:19.376325Z'
type: system.feeds.sync.group_started
```
