### ISSUE TITLE
[ANCHORE] Feed sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#373]
```
details: {}
id: 7e70df7d566d4bb299b9f99ae79db3fe
level: info
message: Feed sync completed
resource:
  id: vulndb
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T05:52:33.679648Z'
type: system.feeds.sync.feed_completed
```
