### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#374]
```
details: {}
id: 444d027c136c41158d77229af0cc7cf3
level: info
message: Feed sync started
resource:
  id: nvdv2
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T05:52:33.740520Z'
type: system.feeds.sync.feed_started
```
