### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#376]
```
details:
  result:
    group: nvdv2:cves
    status: success
    total_time_seconds: 14976.884857177734
    updated_image_count: 0
    updated_record_count: 144013
id: d4238e7306b4484ea87c494f287efde8
level: info
message: Feed group sync completed
resource:
  id: nvdv2/nvdv2:cves
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:11.007984Z'
type: system.feeds.sync.group_completed
```
