### ISSUE TITLE
[ANCHORE] Feed sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#377]
```
details: {}
id: f0d3877f04894f0d83f167ac8782808c
level: info
message: Feed sync completed
resource:
  id: nvdv2
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:11.320723Z'
type: system.feeds.sync.feed_completed
```
