### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#378]
```
details: {}
id: 4f64b284be594aacb4f1be7bf6cdb01a
level: info
message: Feed sync started
resource:
  id: microsoft
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:11.377101Z'
type: system.feeds.sync.feed_started
```
