### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#379]
```
details: {}
id: f266d8ef691b40d2bb628c75039b9f4c
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11646
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:11.569759Z'
type: system.feeds.sync.group_started
```
