### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#38]
```
details: {}
id: 69108614997d439baf2119892f74cc67
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11572
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:17.614787Z'
type: system.feeds.sync.group_started
```
