### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#380]
```
details:
  result:
    group: msrc:11646
    status: success
    total_time_seconds: 0.18430781364440918
    updated_image_count: 0
    updated_record_count: 0
id: 3161da61008245a184a48c015af97dd7
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11646
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:11.833650Z'
type: system.feeds.sync.group_completed
```
