### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#382]
```
details:
  result:
    group: msrc:10789
    status: success
    total_time_seconds: 0.17113471031188965
    updated_image_count: 0
    updated_record_count: 0
id: 0cba7d8b91d04c07a4ec0fa986c4ca41
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10789
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:12.170861Z'
type: system.feeds.sync.group_completed
```
