### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#384]
```
details:
  result:
    group: msrc:11644
    status: success
    total_time_seconds: 0.22243881225585938
    updated_image_count: 0
    updated_record_count: 0
id: c6e074193c6a4315bfe164a5a4b61b2e
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11644
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:12.547233Z'
type: system.feeds.sync.group_completed
```
