### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#385]
```
details: {}
id: f9a7930b15094e22b98b0c8acc214f21
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11713
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:12.611016Z'
type: system.feeds.sync.group_started
```
