### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#388]
```
details:
  result:
    group: msrc:11645
    status: success
    total_time_seconds: 0.1710500717163086
    updated_image_count: 0
    updated_record_count: 0
id: d18d1764e3284733b5f09c1b4f753571
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11645
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:13.226918Z'
type: system.feeds.sync.group_completed
```
