### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#389]
```
details: {}
id: 8599da5d5b254c1eb5862430ca621cc8
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11647
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:13.293016Z'
type: system.feeds.sync.group_started
```
