### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#39]
```
details:
  result:
    group: msrc:11572
    status: success
    total_time_seconds: 0.07105302810668945
    updated_image_count: 0
    updated_record_count: 0
id: 33586a4a710e463c9bd71ad2eed5baac
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11572
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:17.765622Z'
type: system.feeds.sync.group_completed
```
