### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#391]
```
details: {}
id: cf57ce16e1d340a7bde6c745bed9b948
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:products
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:13.593678Z'
type: system.feeds.sync.group_started
```
