### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#392]
```
details:
  result:
    group: msrc:products
    status: success
    total_time_seconds: 0.06599879264831543
    updated_image_count: 0
    updated_record_count: 0
id: 0e9aee904094460c9395c485a2ee619f
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:products
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:13.730881Z'
type: system.feeds.sync.group_completed
```
