### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#394]
```
details:
  result:
    group: msrc:10951
    status: success
    total_time_seconds: 0.2090926170349121
    updated_image_count: 0
    updated_record_count: 0
id: 7e193a28c0894608b180e82426d43908
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10951
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:14.090045Z'
type: system.feeds.sync.group_completed
```
