### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#396]
```
details:
  result:
    group: msrc:11715
    status: success
    total_time_seconds: 0.14249610900878906
    updated_image_count: 0
    updated_record_count: 0
id: 47111b5e184e444b930beb74f27cd525
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11715
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:14.371644Z'
type: system.feeds.sync.group_completed
```
