### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#398]
```
details:
  result:
    group: msrc:11572
    status: success
    total_time_seconds: 0.2153012752532959
    updated_image_count: 0
    updated_record_count: 0
id: a1450d5277c942eb8eb5e426b1015e82
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11572
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:14.728492Z'
type: system.feeds.sync.group_completed
```
