### ISSUE TITLE
[ANCHORE] Feeds sync task started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#4]
```
details:
  sync_feed_types:
  - microsoft
  - github
id: 87e1ba8488634e8c9c0bd09d16897e45
level: info
message: Feeds sync task started
resource:
  id: null
  type: feeds
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:13.760167Z'
type: system.feeds.sync.started
```
