### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#400]
```
details:
  result:
    group: msrc:10543
    status: success
    total_time_seconds: 0.20397043228149414
    updated_image_count: 0
    updated_record_count: 0
id: 63d3788eb7104a759bbb8a193112d112
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10543
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:15.087954Z'
type: system.feeds.sync.group_completed
```
