### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#402]
```
details:
  result:
    group: msrc:11497
    status: success
    total_time_seconds: 0.1383671760559082
    updated_image_count: 0
    updated_record_count: 0
id: e396bc02e29f4d53acd5a940d2d58e93
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11497
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:15.374209Z'
type: system.feeds.sync.group_completed
```
