### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#403]
```
details: {}
id: d0692bd9fb604a76a8c157a9b6b4ef57
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10735
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:15.435366Z'
type: system.feeds.sync.group_started
```
