### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#405]
```
details: {}
id: 357c9e7b01a041dcbf43dd76a6ac3be6
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11563
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:15.754167Z'
type: system.feeds.sync.group_started
```
