### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#408]
```
details:
  result:
    group: msrc:10853
    status: success
    total_time_seconds: 0.14451861381530762
    updated_image_count: 0
    updated_record_count: 0
id: 17154b34484d4c13ad08a2f55ada96ad
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10853
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:16.326550Z'
type: system.feeds.sync.group_completed
```
