### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#409]
```
details: {}
id: 105255b9b69041e8b614845a7e9258a6
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11714
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:16.393300Z'
type: system.feeds.sync.group_started
```
