### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#41]
```
details:
  result:
    group: msrc:10543
    status: success
    total_time_seconds: 0.0691230297088623
    updated_image_count: 0
    updated_record_count: 0
id: 7fa3787ba75642b8b2b699d1f3d8e4f2
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10543
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:17.982686Z'
type: system.feeds.sync.group_completed
```
