### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#410]
```
details:
  result:
    group: msrc:11714
    status: success
    total_time_seconds: 0.13442039489746094
    updated_image_count: 0
    updated_record_count: 0
id: 600545f3114742f69b60acb045e8e90b
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11714
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:16.605017Z'
type: system.feeds.sync.group_completed
```
