### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#411]
```
details: {}
id: 0ead0588398d4d88b68ab65e842ca574
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10379
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:16.667017Z'
type: system.feeds.sync.group_started
```
