### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#414]
```
details:
  result:
    group: msrc:10729
    status: success
    total_time_seconds: 0.13916754722595215
    updated_image_count: 0
    updated_record_count: 0
id: 85e4cfd0d6644222aecdc37cf44d90cd
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10729
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:17.211835Z'
type: system.feeds.sync.group_completed
```
