### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#42]
```
details: {}
id: 55ffa19e75ca4026ab0e00d667ed3e7e
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11497
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:18.045975Z'
type: system.feeds.sync.group_started
```
