### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#420]
```
details:
  result:
    group: msrc:11569
    status: success
    total_time_seconds: 0.13379526138305664
    updated_image_count: 0
    updated_record_count: 0
id: e9242132c6564106bb072f71c778b8fe
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11569
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:18.059176Z'
type: system.feeds.sync.group_completed
```
