### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#421]
```
details: {}
id: 213f2c830dc0470387d13ab59a7dc6c6
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11712
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:18.124865Z'
type: system.feeds.sync.group_started
```
