### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#423]
```
details: {}
id: 0d511b3f46c949c0b839fe8c1bf36b27
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11571
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:18.403675Z'
type: system.feeds.sync.group_started
```
