### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#424]
```
details:
  result:
    group: msrc:11571
    status: success
    total_time_seconds: 0.1335892677307129
    updated_image_count: 0
    updated_record_count: 0
id: 8d2c7e0ad46a49deb27af9fd57672cd0
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11571
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:18.619579Z'
type: system.feeds.sync.group_completed
```
