### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#429]
```
details: {}
id: b5ce11a011ac44d5ac84c24d0a384d8f
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11453
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:19.354288Z'
type: system.feeds.sync.group_started
```
