### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#43]
```
details:
  result:
    group: msrc:11497
    status: success
    total_time_seconds: 0.0856773853302002
    updated_image_count: 0
    updated_record_count: 0
id: b571c24704c34a9f80fe5fc1db2d0481
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11497
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:18.227286Z'
type: system.feeds.sync.group_completed
```
