### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#431]
```
details: {}
id: e9d3f1c2926c47fa9bf4ff7b6f2c6124
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10855
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:19.719371Z'
type: system.feeds.sync.group_started
```
