### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#434]
```
details:
  result:
    group: msrc:10788
    status: success
    total_time_seconds: 0.15133976936340332
    updated_image_count: 0
    updated_record_count: 0
id: 1366db9b2072445d9b4090ba79480634
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10788
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:20.246943Z'
type: system.feeds.sync.group_completed
```
