### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#436]
```
details:
  result:
    group: msrc:11499
    status: success
    total_time_seconds: 0.1376204490661621
    updated_image_count: 0
    updated_record_count: 0
id: ce05c2fb07524ac8908602d3c68d74a6
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11499
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:20.534091Z'
type: system.feeds.sync.group_completed
```
