### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#439]
```
details: {}
id: 42822a48a0884223a40440e4d73647b3
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11568
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:20.956735Z'
type: system.feeds.sync.group_started
```
