### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#440]
```
details:
  result:
    group: msrc:11568
    status: success
    total_time_seconds: 0.17366957664489746
    updated_image_count: 0
    updated_record_count: 0
id: 243203f8022a498e9e3584eefab9e1f0
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11568
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:21.227512Z'
type: system.feeds.sync.group_completed
```
