### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#442]
```
details:
  result:
    group: msrc:11570
    status: success
    total_time_seconds: 0.16342496871948242
    updated_image_count: 0
    updated_record_count: 0
id: 565d7cfd95974e1881b9b95922bbf0b4
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11570
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:21.559920Z'
type: system.feeds.sync.group_completed
```
