### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#444]
```
details:
  result:
    group: msrc:11583
    status: success
    total_time_seconds: 0.1500716209411621
    updated_image_count: 0
    updated_record_count: 0
id: 92d5d4490406408185386aa5d7e4c622
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11583
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:21.871278Z'
type: system.feeds.sync.group_completed
```
