### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#446]
```
details:
  result:
    group: msrc:11466
    status: success
    total_time_seconds: 0.13544058799743652
    updated_image_count: 0
    updated_record_count: 0
id: c2eab197d51945a69ae60a06a0ca6f2a
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11466
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:22.209822Z'
type: system.feeds.sync.group_completed
```
