### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#448]
```
details: {}
id: 626e2a39c6c14a0892f85da4c3ed31ba
level: info
message: Feed sync started
resource:
  id: github
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:22.441986Z'
type: system.feeds.sync.feed_started
```
