### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#45]
```
details:
  result:
    group: msrc:10735
    status: success
    total_time_seconds: 0.08046889305114746
    updated_image_count: 0
    updated_record_count: 0
id: b5ffe3436529421bb3a2912e6e9e5971
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10735
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:18.462114Z'
type: system.feeds.sync.group_completed
```
