### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#450]
```
details:
  result:
    group: github:gem
    status: success
    total_time_seconds: 0.1550436019897461
    updated_image_count: 0
    updated_record_count: 0
id: 9a3f7c2d560b4984ae7fb67d15b92f05
level: info
message: Feed group sync completed
resource:
  id: github/github:gem
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:22.910803Z'
type: system.feeds.sync.group_completed
```
