### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#451]
```
details: {}
id: 4ebb93f912a94c31aec5c3bb249ce8b7
level: info
message: Feed group sync started
resource:
  id: github/github:npm
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:22.992480Z'
type: system.feeds.sync.group_started
```
