### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#452]
```
details:
  result:
    group: github:npm
    status: success
    total_time_seconds: 0.15073776245117188
    updated_image_count: 0
    updated_record_count: 0
id: 53a3bbade4a24c0dabe280d2298cf64e
level: info
message: Feed group sync completed
resource:
  id: github/github:npm
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:23.231818Z'
type: system.feeds.sync.group_completed
```
