### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#455]
```
details: {}
id: 26d93614cd3942cb892f041baad07f76
level: info
message: Feed group sync started
resource:
  id: github/github:python
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:24.020854Z'
type: system.feeds.sync.group_started
```
