### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#456]
```
details:
  result:
    group: github:python
    status: success
    total_time_seconds: 0.07323646545410156
    updated_image_count: 0
    updated_record_count: 0
id: 1191ecdefe5e4b619390bb553873f4ef
level: info
message: Feed group sync completed
resource:
  id: github/github:python
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:24.214828Z'
type: system.feeds.sync.group_completed
```
