### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#457]
```
details: {}
id: f46cf54b47034e4682f502dd618046ac
level: info
message: Feed group sync started
resource:
  id: github/github:java
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:24.281147Z'
type: system.feeds.sync.group_started
```
