### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#458]
```
details:
  result:
    group: github:java
    status: success
    total_time_seconds: 0.182891845703125
    updated_image_count: 0
    updated_record_count: 0
id: 4d7c2974a1774873b2bd8e4229a255b8
level: info
message: Feed group sync completed
resource:
  id: github/github:java
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:24.574801Z'
type: system.feeds.sync.group_completed
```
