### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#46]
```
details: {}
id: e756bb04cce64792a695a9e28167ffc0
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11563
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:18.531930Z'
type: system.feeds.sync.group_started
```
