### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#460]
```
details:
  result:
    group: github:composer
    status: success
    total_time_seconds: 0.07871603965759277
    updated_image_count: 0
    updated_record_count: 0
id: 555623b2dccb4ef6b78e650346a4ec45
level: info
message: Feed group sync completed
resource:
  id: github/github:composer
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:24.811595Z'
type: system.feeds.sync.group_completed
```
