### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#462]
```
details: {}
id: 43bb3a7e48444123b758dc317b07cdf8
level: info
message: Feed sync started
resource:
  id: packages
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:24.952137Z'
type: system.feeds.sync.feed_started
```
