### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#463]
```
details: {}
id: 1e29653478844e03b012dd6c7da03028
level: info
message: Feed group sync started
resource:
  id: packages/gem
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:25.167528Z'
type: system.feeds.sync.group_started
```
