### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#464]
```
details:
  result:
    group: gem
    status: success
    total_time_seconds: 1.655839204788208
    updated_image_count: 0
    updated_record_count: 0
id: 8e1fa54d5e434e3cbca85eac46f215e1
level: info
message: Feed group sync completed
resource:
  id: packages/gem
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:26.916720Z'
type: system.feeds.sync.group_completed
```
