### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#465]
```
details: {}
id: b58c460a8d82460f86a7f31c0023e253
level: info
message: Feed group sync started
resource:
  id: packages/npm
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:02:27.014628Z'
type: system.feeds.sync.group_started
```
