### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#466]
```
details:
  result:
    group: npm
    status: success
    total_time_seconds: 2002.563791513443
    updated_image_count: 0
    updated_record_count: 490000
id: 879a1f93c57b416ca26e0cd800bb15e5
level: info
message: Feed group sync completed
resource:
  id: packages/npm
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:35:49.672374Z'
type: system.feeds.sync.group_completed
```
