### ISSUE TITLE
[ANCHORE] Feed sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#467]
```
details: {}
id: 542bf11e0a6b4f979943d5a960c1ce14
level: info
message: Feed sync completed
resource:
  id: packages
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:35:49.793672Z'
type: system.feeds.sync.feed_completed
```
