### ISSUE TITLE
[ANCHORE] Feeds sync task completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#468]
```
details:
  sync_feed_types:
  - vulnerabilities
  - packages
  - nvdv2
  - vulndb
  - microsoft
  - github
id: 1d74231b6931433ebb26505db5d11917
level: info
message: Feeds sync task completed
resource:
  id: null
  type: feeds
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T10:35:49.849372Z'
type: system.feeds.sync.completed
```
