### ISSUE TITLE
[ANCHORE] Feeds sync task started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#469]
```
details:
  sync_feed_types:
  - vulnerabilities
  - packages
  - nvdv2
  - vulndb
  - microsoft
  - github
id: 657a92fed0fb41cfb9e2912764163c80
level: info
message: Feeds sync task started
resource:
  id: null
  type: feeds
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T14:35:50.146409Z'
type: system.feeds.sync.started
```
