### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#47]
```
details:
  result:
    group: msrc:11563
    status: success
    total_time_seconds: 0.09157276153564453
    updated_image_count: 0
    updated_record_count: 0
id: 90d3e36d8a7f46ceaff38bd5308160f4
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11563
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:18.730779Z'
type: system.feeds.sync.group_completed
```
