### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#472]
```
details:
  result:
    group: alpine:3.11
    status: success
    total_time_seconds: 0.15677857398986816
    updated_image_count: 0
    updated_record_count: 0
id: 77c720730fa0442c97c298b50eefbab9
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.11
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T14:35:50.768205Z'
type: system.feeds.sync.group_completed
```
