### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#474]
```
details:
  result:
    group: alpine:3.10
    status: success
    total_time_seconds: 0.20131349563598633
    updated_image_count: 0
    updated_record_count: 0
id: 629e6bc6590748a4a102b0ec91fdb69a
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T14:35:51.123543Z'
type: system.feeds.sync.group_completed
```
