### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#475]
```
details: {}
id: f82631c5af9c44399ab4b6b3a4abbbfc
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.4
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T14:35:51.184112Z'
type: system.feeds.sync.group_started
```
