### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#477]
```
details: {}
id: c26c6b441b1a4f86a1a5c266556e9e64
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.3
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T14:35:51.474915Z'
type: system.feeds.sync.group_started
```
