### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#478]
```
details:
  result:
    group: alpine:3.3
    status: success
    total_time_seconds: 0.13767504692077637
    updated_image_count: 0
    updated_record_count: 0
id: 8e45cb479e374a7eaee4f39d5b1cfa25
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.3
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T14:35:51.689260Z'
type: system.feeds.sync.group_completed
```
