### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#482]
```
details:
  result:
    group: centos:7
    status: success
    total_time_seconds: 65.95459222793579
    updated_image_count: 0
    updated_record_count: 1049
id: 18b54ae79ab247f1bb5857d9bd4aa796
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/centos:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T14:36:58.174868Z'
type: system.feeds.sync.group_completed
```
