### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#483]
```
details: {}
id: 8424ebc3431b4146a2d6c0b5f656b454
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/centos:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T14:36:58.251314Z'
type: system.feeds.sync.group_started
```
