### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#484]
```
details:
  result:
    group: centos:8
    status: success
    total_time_seconds: 24.758894443511963
    updated_image_count: 0
    updated_record_count: 260
id: ebe8d9f45647471788878877201d7c58
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/centos:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T14:37:23.084597Z'
type: system.feeds.sync.group_completed
```
