### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#486]
```
details:
  result:
    group: debian:10
    status: success
    total_time_seconds: 430.61365270614624
    updated_image_count: 0
    updated_record_count: 19229
id: fbd0b04115a04e02a793b3a18a8d93cd
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/debian:10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T14:44:33.850780Z'
type: system.feeds.sync.group_completed
```
