### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#487]
```
details: {}
id: 7b3f3f1e25af437c83423343c84b9c4e
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/debian:11
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T14:44:33.926774Z'
type: system.feeds.sync.group_started
```
