### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#488]
```
details:
  result:
    group: debian:11
    status: success
    total_time_seconds: 422.3290820121765
    updated_image_count: 0
    updated_record_count: 19101
id: ca731caf84a24417991446b63f62861a
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/debian:11
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T14:51:36.361378Z'
type: system.feeds.sync.group_completed
```
