### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#489]
```
details: {}
id: a1ff98b8cabf49cbb0c7a144f4b9a8b3
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/debian:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T14:51:36.450080Z'
type: system.feeds.sync.group_started
```
