### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#49]
```
details:
  result:
    group: msrc:10853
    status: success
    total_time_seconds: 0.09480714797973633
    updated_image_count: 0
    updated_record_count: 0
id: f6d6ef5566784087a0ecbaa959282fbf
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10853
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:18.987749Z'
type: system.feeds.sync.group_completed
```
