### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#490]
```
details:
  result:
    group: debian:8
    status: success
    total_time_seconds: 495.6521873474121
    updated_image_count: 0
    updated_record_count: 23561
id: 9ed9fb76aa7347c19ed8d7165ba2dfb5
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/debian:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T14:59:52.172716Z'
type: system.feeds.sync.group_completed
```
