### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#491]
```
details: {}
id: 1c2eb61b0e334681ad157381cbacd950
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/debian:9
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T14:59:52.263942Z'
type: system.feeds.sync.group_started
```
