### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#492]
```
details:
  result:
    group: debian:9
    status: success
    total_time_seconds: 462.8335304260254
    updated_image_count: 0
    updated_record_count: 21787
id: 19e46e9df18d4e2c8140a544c441c167
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/debian:9
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:07:35.170603Z'
type: system.feeds.sync.group_completed
```
