### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#493]
```
details: {}
id: 12dc16756f714e37ba211279a8a06bd2
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/debian:unstable
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:07:35.251292Z'
type: system.feeds.sync.group_started
```
