### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#494]
```
details:
  result:
    group: debian:unstable
    status: success
    total_time_seconds: 458.91405272483826
    updated_image_count: 0
    updated_record_count: 21078
id: 60276269bad24a2da6c8d34a01901640
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/debian:unstable
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:15:14.245563Z'
type: system.feeds.sync.group_completed
```
