### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#495]
```
details: {}
id: aa327a3d87004fe787725a8b360a6abd
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ol:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:15:14.322819Z'
type: system.feeds.sync.group_started
```
