### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#496]
```
details:
  result:
    group: ol:5
    status: success
    total_time_seconds: 84.5472264289856
    updated_image_count: 0
    updated_record_count: 1246
id: 927ba024b1a24e8b9cb7c5934aefd3f4
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ol:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:16:38.943516Z'
type: system.feeds.sync.group_completed
```
