### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#497]
```
details: {}
id: 6d255ed9fe6c4a3ea624a98a12ea0fac
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ol:6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:16:39.023923Z'
type: system.feeds.sync.group_started
```
