### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#498]
```
details:
  result:
    group: ol:6
    status: success
    total_time_seconds: 108.51996278762817
    updated_image_count: 0
    updated_record_count: 1518
id: e300211d0e124b6ab367229c7908bbf8
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ol:6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:18:27.619352Z'
type: system.feeds.sync.group_completed
```
