### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#499]
```
details: {}
id: 12d1d1b7685a4f608d957b844104af65
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ol:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:18:27.691885Z'
type: system.feeds.sync.group_started
```
