### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#5]
```
details: {}
id: a0e91f2c65e64100acdd4e49b6f8152d
level: info
message: Feed sync started
resource:
  id: microsoft
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:13.946750Z'
type: system.feeds.sync.feed_started
```
