### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#50]
```
details: {}
id: 428da390be414da3a15ff92ea56d14ca
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11714
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:19.059920Z'
type: system.feeds.sync.group_started
```
