### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#500]
```
details:
  result:
    group: ol:7
    status: success
    total_time_seconds: 113.23114109039307
    updated_image_count: 0
    updated_record_count: 1194
id: c86a24b5442544e18580e438da71c75c
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ol:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:20:20.996694Z'
type: system.feeds.sync.group_completed
```
