### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#502]
```
details:
  result:
    group: ol:8
    status: success
    total_time_seconds: 21.5670063495636
    updated_image_count: 0
    updated_record_count: 185
id: cf19ac2788fb48829a55218c88db521e
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ol:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:20:42.723539Z'
type: system.feeds.sync.group_completed
```
