### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#503]
```
details: {}
id: a9fdeb4bc4f04a5f872a7614f797f3ce
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/rhel:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:20:42.798962Z'
type: system.feeds.sync.group_started
```
