### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#504]
```
details:
  result:
    group: rhel:5
    status: success
    total_time_seconds: 186.57994174957275
    updated_image_count: 0
    updated_record_count: 7237
id: 5965e9bb2341404f872b0c08e5d436d0
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/rhel:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:23:49.448467Z'
type: system.feeds.sync.group_completed
```
