### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#505]
```
details: {}
id: b48c158d1a244685a2e71dbea964a72f
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/rhel:6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:23:49.529144Z'
type: system.feeds.sync.group_started
```
