### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#506]
```
details:
  result:
    group: rhel:6
    status: success
    total_time_seconds: 168.49685907363892
    updated_image_count: 0
    updated_record_count: 6835
id: 4bc6513a148343b0b428b78c769418d2
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/rhel:6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:26:38.100922Z'
type: system.feeds.sync.group_completed
```
