### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#508]
```
details:
  result:
    group: rhel:7
    status: success
    total_time_seconds: 148.38092517852783
    updated_image_count: 0
    updated_record_count: 5899
id: ef1dd58e28b74e9ea55387d53ac97cd6
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/rhel:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:29:06.626093Z'
type: system.feeds.sync.group_completed
```
