### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#509]
```
details: {}
id: 03da8f0b7d8a4264a0a166b78b728bea
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:18.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:29:06.699250Z'
type: system.feeds.sync.group_started
```
