### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#51]
```
details:
  result:
    group: msrc:11714
    status: success
    total_time_seconds: 0.07552719116210938
    updated_image_count: 0
    updated_record_count: 0
id: 6f491519f8cc461ea498918699b178c7
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11714
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:19.223124Z'
type: system.feeds.sync.group_completed
```
