### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#510]
```
details:
  result:
    group: ubuntu:18.10
    status: success
    total_time_seconds: 129.2101800441742
    updated_image_count: 0
    updated_record_count: 8364
id: d4c9ab1d3468421d864d42181e1b80d6
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:18.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:31:15.981472Z'
type: system.feeds.sync.group_completed
```
