### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#512]
```
details:
  result:
    group: ubuntu:19.04
    status: success
    total_time_seconds: 143.25941109657288
    updated_image_count: 0
    updated_record_count: 8631
id: 46cdc0f0aeac43bbb003ea88fb5b2fce
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:19.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:33:39.390669Z'
type: system.feeds.sync.group_completed
```
