### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#513]
```
details: {}
id: 46b2779177894fd0b9654029cbebeafe
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:19.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:33:39.468942Z'
type: system.feeds.sync.group_started
```
