### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#514]
```
details:
  result:
    group: ubuntu:19.10
    status: success
    total_time_seconds: 124.06944847106934
    updated_image_count: 0
    updated_record_count: 7803
id: 209b90267ce749fc8f9d81f6e5a6fa1f
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:19.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:35:43.609547Z'
type: system.feeds.sync.group_completed
```
