### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#516]
```
details:
  result:
    group: ubuntu:20.04
    status: success
    total_time_seconds: 97.17362689971924
    updated_image_count: 0
    updated_record_count: 6858
id: 0700e2cabd1b437f8625c4b38d5beabc
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:20.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:20.946385Z'
type: system.feeds.sync.group_completed
```
