### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#517]
```
details: {}
id: 2227d76ba05748d5902c8e09a3ede526
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:21.019685Z'
type: system.feeds.sync.group_started
```
