### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#518]
```
details:
  result:
    group: alpine:3.6
    status: success
    total_time_seconds: 0.18328404426574707
    updated_image_count: 0
    updated_record_count: 0
id: 0bfb06ce3e56415ba3e34b6c7e9efdaf
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:21.277971Z'
type: system.feeds.sync.group_completed
```
