### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#519]
```
details: {}
id: b0e8a5072ed14e1b974fd139d2c1a006
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:13.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:21.341940Z'
type: system.feeds.sync.group_started
```
