### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#520]
```
details:
  result:
    group: ubuntu:13.04
    status: success
    total_time_seconds: 0.295926570892334
    updated_image_count: 0
    updated_record_count: 2
id: 617578fdd73342dabacb6ef945ef1d51
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:13.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:21.711521Z'
type: system.feeds.sync.group_completed
```
