### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#522]
```
details:
  result:
    group: alpine:3.8
    status: success
    total_time_seconds: 0.2908616065979004
    updated_image_count: 0
    updated_record_count: 0
id: ec236e857cfd42e9acf6880e54e9d039
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:22.138784Z'
type: system.feeds.sync.group_completed
```
