### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#523]
```
details: {}
id: c145d7868560447680e5f57aef19c125
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/centos:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:22.197498Z'
type: system.feeds.sync.group_started
```
