### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#524]
```
details:
  result:
    group: centos:5
    status: success
    total_time_seconds: 0.1966242790222168
    updated_image_count: 0
    updated_record_count: 0
id: 48d30e2fe86841b184bb49274e6b0220
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/centos:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:22.466550Z'
type: system.feeds.sync.group_completed
```
