### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#525]
```
details: {}
id: daf3a3dec4734403bc62f726ad959ce1
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:12.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:22.524703Z'
type: system.feeds.sync.group_started
```
