### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#527]
```
details: {}
id: 27242a73adc64e4882ab9066e1808b3e
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/amzn:2
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:22.926286Z'
type: system.feeds.sync.group_started
```
