### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#529]
```
details: {}
id: 1a80022906084e5db1182bac25bcccbd
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:16.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:23.173092Z'
type: system.feeds.sync.group_started
```
