### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#53]
```
details:
  result:
    group: msrc:10379
    status: success
    total_time_seconds: 0.08259153366088867
    updated_image_count: 0
    updated_record_count: 0
id: 15b672d6de724c37a8746ca18492e2b3
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10379
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:19.456762Z'
type: system.feeds.sync.group_completed
```
