### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#530]
```
details:
  result:
    group: ubuntu:16.10
    status: success
    total_time_seconds: 0.21026301383972168
    updated_image_count: 0
    updated_record_count: 0
id: f2c1d9e9fc5c4168a3ab6d945ad34f34
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:16.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:23.466196Z'
type: system.feeds.sync.group_completed
```
