### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#532]
```
details:
  result:
    group: ubuntu:12.10
    status: success
    total_time_seconds: 0.252795934677124
    updated_image_count: 0
    updated_record_count: 2
id: c0d96043ddbd45c58a5c7e0d062b86b8
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:12.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:23.869173Z'
type: system.feeds.sync.group_completed
```
