### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#533]
```
details: {}
id: 4a625e861221490a890bede79585e81f
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:14.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:23.930042Z'
type: system.feeds.sync.group_started
```
