### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#534]
```
details:
  result:
    group: ubuntu:14.10
    status: success
    total_time_seconds: 0.2037675380706787
    updated_image_count: 0
    updated_record_count: 0
id: d706e4df241341189d77016483ee9b7e
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:14.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:24.221846Z'
type: system.feeds.sync.group_completed
```
