### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#536]
```
details:
  result:
    group: ubuntu:16.04
    status: success
    total_time_seconds: 0.5021615028381348
    updated_image_count: 0
    updated_record_count: 20
id: 17ed1860c0df4d499cedfe5490b49b65
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:16.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:24.880245Z'
type: system.feeds.sync.group_completed
```
