### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#538]
```
details:
  result:
    group: ubuntu:14.04
    status: success
    total_time_seconds: 0.5032439231872559
    updated_image_count: 0
    updated_record_count: 19
id: f8e6fead69dc4035a45923036faedb56
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:14.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:25.534083Z'
type: system.feeds.sync.group_completed
```
