### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#540]
```
details:
  result:
    group: ubuntu:15.10
    status: success
    total_time_seconds: 0.2945592403411865
    updated_image_count: 0
    updated_record_count: 0
id: 11d0b1f6cb484c7aa80b02f9bf507cf2
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:15.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:25.980358Z'
type: system.feeds.sync.group_completed
```
