### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#541]
```
details: {}
id: 065dfa9fcd8e49308c04e74d57aee467
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:15.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:26.061794Z'
type: system.feeds.sync.group_started
```
