### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#542]
```
details:
  result:
    group: ubuntu:15.04
    status: success
    total_time_seconds: 0.21760797500610352
    updated_image_count: 0
    updated_record_count: 0
id: c00e3762cd274ce38aab4d6fbb6dde44
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:15.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:26.351872Z'
type: system.feeds.sync.group_completed
```
