### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#543]
```
details: {}
id: 97b790a03f6848bf9c51ff12a7571177
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:17.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:26.424287Z'
type: system.feeds.sync.group_started
```
