### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#544]
```
details:
  result:
    group: ubuntu:17.04
    status: success
    total_time_seconds: 0.21006560325622559
    updated_image_count: 0
    updated_record_count: 0
id: 2a0d879674114fc286b2415a0b5bad78
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:17.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:26.720747Z'
type: system.feeds.sync.group_completed
```
