### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#548]
```
details:
  result:
    group: centos:6
    status: success
    total_time_seconds: 0.20732808113098145
    updated_image_count: 0
    updated_record_count: 0
id: 5c44cc459ecd4bc78014291f3f2429e5
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/centos:6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:27.508457Z'
type: system.feeds.sync.group_completed
```
