### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#55]
```
details:
  result:
    group: msrc:10729
    status: success
    total_time_seconds: 1.4495410919189453
    updated_image_count: 0
    updated_record_count: 0
id: d73cd17f04cf4fd7a1bc9d70d76c183d
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10729
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:21.060216Z'
type: system.feeds.sync.group_completed
```
