### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#550]
```
details:
  result:
    group: alpine:3.7
    status: success
    total_time_seconds: 0.18042945861816406
    updated_image_count: 0
    updated_record_count: 0
id: 1072f1d5d1d74b29a8f9ff2e0ae1555f
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:27.832475Z'
type: system.feeds.sync.group_completed
```
