### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#552]
```
details:
  result:
    group: ubuntu:18.04
    status: success
    total_time_seconds: 0.46764183044433594
    updated_image_count: 0
    updated_record_count: 20
id: c60e751f981544ec8a6191204a903ea2
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:18.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:28.446667Z'
type: system.feeds.sync.group_completed
```
