### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#553]
```
details: {}
id: e9f9f3a5784b416b9b81fe790db95fd9
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.9
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:28.513147Z'
type: system.feeds.sync.group_started
```
