### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#554]
```
details:
  result:
    group: alpine:3.9
    status: success
    total_time_seconds: 0.22965550422668457
    updated_image_count: 0
    updated_record_count: 0
id: f360d9ceb67c4f8385a46f849007be6d
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.9
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:28.823258Z'
type: system.feeds.sync.group_completed
```
