### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#555]
```
details: {}
id: 5ccd55a158cf4eb4bf48afce5d2daf94
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/rhel:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:28.885853Z'
type: system.feeds.sync.group_started
```
