### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#556]
```
details:
  result:
    group: rhel:8
    status: success
    total_time_seconds: 0.27090024948120117
    updated_image_count: 0
    updated_record_count: 3
id: 04d407acb50e4b73bedaaca90963e4b5
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/rhel:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:29.230907Z'
type: system.feeds.sync.group_completed
```
