### ISSUE TITLE
[ANCHORE] Feed sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#557]
```
details: {}
id: e35c0c26a4d44a31aee14358405c55c6
level: info
message: Feed sync completed
resource:
  id: vulnerabilities
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:29.291039Z'
type: system.feeds.sync.feed_completed
```
