### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#558]
```
details: {}
id: ce5c5a9a73044a2ba566e4444e2d9036
level: info
message: Feed sync started
resource:
  id: vulndb
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T15:37:29.349057Z'
type: system.feeds.sync.feed_started
```
