### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#57]
```
details:
  result:
    group: msrc:10816
    status: success
    total_time_seconds: 0.825373649597168
    updated_image_count: 0
    updated_record_count: 0
id: 97c40df3c96449d89f31ccf8336f8c83
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10816
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:22.045409Z'
type: system.feeds.sync.group_completed
```
