### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#575]
```
details:
  result:
    group: vulndb:vulnerabilities
    status: success
    total_time_seconds: 4552.1391932964325
    updated_image_count: 0
    updated_record_count: 223000
id: 454c0c54e9264ac5921cb0eb57609044
level: info
message: Feed group sync completed
resource:
  id: vulndb/vulndb:vulnerabilities
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:21.815796Z'
type: system.feeds.sync.group_completed
```
