### ISSUE TITLE
[ANCHORE] Feed sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#576]
```
details: {}
id: 5f7a799d178943fe9b0f74030c0e8711
level: info
message: Feed sync completed
resource:
  id: vulndb
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:22.500834Z'
type: system.feeds.sync.feed_completed
```
