### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#577]
```
details: {}
id: f4e320023c80403e9c6961c3334d9611
level: info
message: Feed sync started
resource:
  id: nvdv2
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:22.559555Z'
type: system.feeds.sync.feed_started
```
