### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#578]
```
details: {}
id: 83139b3714574560b835840a30e3efbc
level: info
message: Feed group sync started
resource:
  id: nvdv2/nvdv2:cves
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:22.760267Z'
type: system.feeds.sync.group_started
```
