### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#579]
```
details:
  result:
    group: nvdv2:cves
    status: success
    total_time_seconds: 24.30343985557556
    updated_image_count: 0
    updated_record_count: 277
id: a31c1858e03a425d93f6b3c277d9b3c9
level: info
message: Feed group sync completed
resource:
  id: nvdv2/nvdv2:cves
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:47.141002Z'
type: system.feeds.sync.group_completed
```
