### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#58]
```
details: {}
id: 97c5e897e4344567a150f4c26ae48cb2
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10952
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:22.108563Z'
type: system.feeds.sync.group_started
```
