### ISSUE TITLE
[ANCHORE] Feed sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#580]
```
details: {}
id: a538f2adee1a4eb890a0a8eb626c2ebb
level: info
message: Feed sync completed
resource:
  id: nvdv2
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:47.212548Z'
type: system.feeds.sync.feed_completed
```
