### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#583]
```
details:
  result:
    group: msrc:10789
    status: success
    total_time_seconds: 0.10603523254394531
    updated_image_count: 0
    updated_record_count: 0
id: a0df2be01ff9440e8a381b451d097412
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10789
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:47.672041Z'
type: system.feeds.sync.group_completed
```
