### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#584]
```
details: {}
id: ebd11f98d3ca40a6a1238d6bad6c2446
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11644
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:47.781833Z'
type: system.feeds.sync.group_started
```
