### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#585]
```
details:
  result:
    group: msrc:11644
    status: success
    total_time_seconds: 0.17845702171325684
    updated_image_count: 0
    updated_record_count: 0
id: 30dca1ddeac1440a857f205b11202206
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11644
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:48.075049Z'
type: system.feeds.sync.group_completed
```
