### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#586]
```
details: {}
id: 74bd5358a4064f4d9a76e022d681dfc5
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11713
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:48.184490Z'
type: system.feeds.sync.group_started
```
