### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#589]
```
details:
  result:
    group: msrc:11645
    status: success
    total_time_seconds: 0.09398365020751953
    updated_image_count: 0
    updated_record_count: 0
id: 5c32bf7d39cb4b33924595e08be4c15b
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11645
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:48.728179Z'
type: system.feeds.sync.group_completed
```
