### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#59]
```
details:
  result:
    group: msrc:10952
    status: success
    total_time_seconds: 0.06759238243103027
    updated_image_count: 0
    updated_record_count: 0
id: d5957e4bf3ae46a5aa7b62fd430d5f57
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10952
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:22.255422Z'
type: system.feeds.sync.group_completed
```
