### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#591]
```
details:
  result:
    group: msrc:11647
    status: success
    total_time_seconds: 0.09134149551391602
    updated_image_count: 0
    updated_record_count: 0
id: 619bc8aa2c40431a8055014636e95f6d
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11647
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:48.956407Z'
type: system.feeds.sync.group_completed
```
