### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#593]
```
details:
  result:
    group: msrc:products
    status: success
    total_time_seconds: 0.05690622329711914
    updated_image_count: 0
    updated_record_count: 0
id: 51875d07fa64435290aa5324a7e339fe
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:products
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:49.155612Z'
type: system.feeds.sync.group_completed
```
