### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#594]
```
details: {}
id: 159bf7ec561847f59b2ba664223aa490
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10951
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:49.294666Z'
type: system.feeds.sync.group_started
```
