### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#599]
```
details:
  result:
    group: msrc:11572
    status: success
    total_time_seconds: 0.09023833274841309
    updated_image_count: 0
    updated_record_count: 0
id: ef3356ba9f644ba78e5d0f63a12c79a6
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11572
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:49.997762Z'
type: system.feeds.sync.group_completed
```
