### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#6]
```
details: {}
id: 845cc2006efe4bb1a96a8a9ec7a9d66d
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10788
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:14.028920Z'
type: system.feeds.sync.group_started
```
