### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#602]
```
details: {}
id: e1ff01858e86473e9d1b54e34f9b12f8
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11497
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:50.437866Z'
type: system.feeds.sync.group_started
```
