### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#603]
```
details:
  result:
    group: msrc:11497
    status: success
    total_time_seconds: 0.08431482315063477
    updated_image_count: 0
    updated_record_count: 0
id: 8e63ecffd401476d9f1222a741520d76
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11497
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:50.598636Z'
type: system.feeds.sync.group_completed
```
