### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#605]
```
details:
  result:
    group: msrc:10735
    status: success
    total_time_seconds: 0.30211567878723145
    updated_image_count: 0
    updated_record_count: 0
id: a14ed5893029449487eb12a3b5c50ff8
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10735
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:51.036365Z'
type: system.feeds.sync.group_completed
```
