### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#607]
```
details:
  result:
    group: msrc:11563
    status: success
    total_time_seconds: 0.08712244033813477
    updated_image_count: 0
    updated_record_count: 0
id: 5785ef4d746d4430bacd4f038a728ac1
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11563
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:51.269711Z'
type: system.feeds.sync.group_completed
```
