### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#608]
```
details: {}
id: 27c6bca628ac4a0f8cdae211e49194b4
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10853
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:51.330958Z'
type: system.feeds.sync.group_started
```
