### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#609]
```
details:
  result:
    group: msrc:10853
    status: success
    total_time_seconds: 0.20232391357421875
    updated_image_count: 0
    updated_record_count: 0
id: 3551d4684d2c4b7e86b6d3cf0cdde0b2
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10853
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:51.607272Z'
type: system.feeds.sync.group_completed
```
