### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#61]
```
details:
  result:
    group: msrc:11569
    status: success
    total_time_seconds: 0.07167577743530273
    updated_image_count: 0
    updated_record_count: 0
id: b5711049732641eabf983b3ccde7eb47
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11569
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:22.472838Z'
type: system.feeds.sync.group_completed
```
