### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#611]
```
details:
  result:
    group: msrc:11714
    status: success
    total_time_seconds: 0.09055829048156738
    updated_image_count: 0
    updated_record_count: 0
id: f231ac0b78f14b079c8750f6a0b9e42c
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11714
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:51.839848Z'
type: system.feeds.sync.group_completed
```
