### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#613]
```
details:
  result:
    group: msrc:10379
    status: success
    total_time_seconds: 0.23366761207580566
    updated_image_count: 0
    updated_record_count: 0
id: 0504e7a3ac7d4a84908bbcea6c2a0402
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10379
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:52.233764Z'
type: system.feeds.sync.group_completed
```
