### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#615]
```
details:
  result:
    group: msrc:10729
    status: success
    total_time_seconds: 0.20473194122314453
    updated_image_count: 0
    updated_record_count: 0
id: 5c581dea8fe346eda19a18c3d5b3d180
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10729
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:52.596021Z'
type: system.feeds.sync.group_completed
```
