### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#616]
```
details: {}
id: 760be7a708d54ee2a0ad99567a134341
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10816
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:52.660820Z'
type: system.feeds.sync.group_started
```
