### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#618]
```
details: {}
id: 5156d35349d94cc98f3e41fcb0fe6969
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10952
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:53.091693Z'
type: system.feeds.sync.group_started
```
