### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#621]
```
details:
  result:
    group: msrc:11569
    status: success
    total_time_seconds: 0.09353184700012207
    updated_image_count: 0
    updated_record_count: 0
id: 8ac2e838aaf246d281a7b85efeb63033
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11569
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:53.482199Z'
type: system.feeds.sync.group_completed
```
