### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#623]
```
details:
  result:
    group: msrc:11712
    status: success
    total_time_seconds: 0.0837240219116211
    updated_image_count: 0
    updated_record_count: 0
id: 79b9b0586d3445199437897cb318a369
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11712
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:53.712137Z'
type: system.feeds.sync.group_completed
```
