### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#626]
```
details: {}
id: c2b2016038cb4194a4bf473123c43989
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10852
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:54.004220Z'
type: system.feeds.sync.group_started
```
