### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#629]
```
details:
  result:
    group: msrc:11454
    status: success
    total_time_seconds: 0.2750682830810547
    updated_image_count: 0
    updated_record_count: 0
id: 2ef23c90a3f34478b1f65b19037b690d
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11454
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:54.727446Z'
type: system.feeds.sync.group_completed
```
