### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#63]
```
details:
  result:
    group: msrc:11712
    status: success
    total_time_seconds: 0.06084847450256348
    updated_image_count: 0
    updated_record_count: 0
id: c0863a4dee554b3bbf20bfb9f104f182
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11712
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:22.682017Z'
type: system.feeds.sync.group_completed
```
