### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#633]
```
details:
  result:
    group: msrc:10855
    status: success
    total_time_seconds: 0.27517056465148926
    updated_image_count: 0
    updated_record_count: 0
id: 21433cac80444231a406de9916413b9d
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10855
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:55.626517Z'
type: system.feeds.sync.group_completed
```
