### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#634]
```
details: {}
id: 9cf89431a52847a9837f5c8a2aa8dab7
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10788
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:55.695265Z'
type: system.feeds.sync.group_started
```
