### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#635]
```
details:
  result:
    group: msrc:10788
    status: success
    total_time_seconds: 0.10062932968139648
    updated_image_count: 0
    updated_record_count: 0
id: dc0afcbbcc43429f8be336e707dfab43
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10788
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:55.879134Z'
type: system.feeds.sync.group_completed
```
