### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#637]
```
details:
  result:
    group: msrc:11499
    status: success
    total_time_seconds: 0.08551549911499023
    updated_image_count: 0
    updated_record_count: 0
id: 2ee8ef89040b4d15be5d73b9339358ee
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11499
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:56.115647Z'
type: system.feeds.sync.group_completed
```
