### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#638]
```
details: {}
id: b7e9a5b5903842a987d34804c9650fed
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11498
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:56.188856Z'
type: system.feeds.sync.group_started
```
