### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#639]
```
details:
  result:
    group: msrc:11498
    status: success
    total_time_seconds: 0.1983034610748291
    updated_image_count: 0
    updated_record_count: 0
id: 169fd3fc189f42a3b5e2ee36afbc9dfe
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11498
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:56.471832Z'
type: system.feeds.sync.group_completed
```
