### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#64]
```
details: {}
id: ba9090548c2b41c9b49fd66387f3b2b9
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11571
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:22.750353Z'
type: system.feeds.sync.group_started
```
