### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#641]
```
details:
  result:
    group: msrc:11568
    status: success
    total_time_seconds: 0.0842137336730957
    updated_image_count: 0
    updated_record_count: 0
id: 8522abe9afac432e91c6c5569d11ee6b
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11568
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:56.699208Z'
type: system.feeds.sync.group_completed
```
