### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#643]
```
details:
  result:
    group: msrc:11570
    status: success
    total_time_seconds: 0.27166247367858887
    updated_image_count: 0
    updated_record_count: 0
id: 71f4c0584b7b4f6c8b1ffc7ae856f144
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11570
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:57.115184Z'
type: system.feeds.sync.group_completed
```
