### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#646]
```
details: {}
id: 385bc0aa7f794baeacb27ad65232bb2f
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11466
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:57.410468Z'
type: system.feeds.sync.group_started
```
