### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#648]
```
details: {}
id: 45b2337caa5448e6bcb753c5f2d4e66b
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11646
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:57.637704Z'
type: system.feeds.sync.group_started
```
