### ISSUE TITLE
[ANCHORE] Feed sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#650]
```
details: {}
id: e8bb3bd25cfe4bddbc9fd46a144ef296
level: info
message: Feed sync completed
resource:
  id: microsoft
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:57.850231Z'
type: system.feeds.sync.feed_completed
```
