### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#651]
```
details: {}
id: e8df66ca654c49f6a4260066b7748fa1
level: info
message: Feed sync started
resource:
  id: github
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:57.906184Z'
type: system.feeds.sync.feed_started
```
