### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#652]
```
details: {}
id: 90f21a935f5e4201abe8aded0d2fabc0
level: info
message: Feed group sync started
resource:
  id: github/github:npm
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:58.115155Z'
type: system.feeds.sync.group_started
```
