### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#653]
```
details:
  result:
    group: github:npm
    status: success
    total_time_seconds: 0.0975346565246582
    updated_image_count: 0
    updated_record_count: 0
id: efd33b3b1e434ddaa0512ddbf242499e
level: info
message: Feed group sync completed
resource:
  id: github/github:npm
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:58.288068Z'
type: system.feeds.sync.group_completed
```
