### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#655]
```
details:
  result:
    group: github:nuget
    status: success
    total_time_seconds: 0.0857384204864502
    updated_image_count: 0
    updated_record_count: 0
id: 26915feea12d43fabb81c63610917950
level: info
message: Feed group sync completed
resource:
  id: github/github:nuget
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:58.529458Z'
type: system.feeds.sync.group_completed
```
