### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#657]
```
details:
  result:
    group: github:python
    status: success
    total_time_seconds: 0.07915210723876953
    updated_image_count: 0
    updated_record_count: 0
id: 674c19e70bc844c5a05f452c95852467
level: info
message: Feed group sync completed
resource:
  id: github/github:python
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:58.739491Z'
type: system.feeds.sync.group_completed
```
