### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#658]
```
details: {}
id: 403b2fe99e294dcbb30940f1051e149f
level: info
message: Feed group sync started
resource:
  id: github/github:java
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:58.813588Z'
type: system.feeds.sync.group_started
```
