### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#659]
```
details:
  result:
    group: github:java
    status: success
    total_time_seconds: 0.08295035362243652
    updated_image_count: 0
    updated_record_count: 0
id: 98f74ef1e1bb40119781591d52251e70
level: info
message: Feed group sync completed
resource:
  id: github/github:java
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:58.972840Z'
type: system.feeds.sync.group_completed
```
