### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#66]
```
details: {}
id: 19bc966ca32649889a8aed5f93a0529b
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10852
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:22.967584Z'
type: system.feeds.sync.group_started
```
