### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#661]
```
details:
  result:
    group: github:composer
    status: success
    total_time_seconds: 0.08119630813598633
    updated_image_count: 0
    updated_record_count: 0
id: 79b902a99e474854b7bbd76594f50117
level: info
message: Feed group sync completed
resource:
  id: github/github:composer
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:59.187084Z'
type: system.feeds.sync.group_completed
```
