### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#663]
```
details:
  result:
    group: github:gem
    status: success
    total_time_seconds: 0.10867643356323242
    updated_image_count: 0
    updated_record_count: 0
id: fda7331d6d6f40febfbc257005b47655
level: info
message: Feed group sync completed
resource:
  id: github/github:gem
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:59.440692Z'
type: system.feeds.sync.group_completed
```
