### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#665]
```
details: {}
id: 787ff46cabff432983fd5e746b43dd13
level: info
message: Feed sync started
resource:
  id: packages
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:53:59.573750Z'
type: system.feeds.sync.feed_started
```
