### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#667]
```
details:
  result:
    group: gem
    status: success
    total_time_seconds: 0.27147889137268066
    updated_image_count: 0
    updated_record_count: 0
id: 510ceace734e49989cd625f7a5b3375c
level: info
message: Feed group sync completed
resource:
  id: packages/gem
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T16:54:00.140595Z'
type: system.feeds.sync.group_completed
```
