### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#67]
```
details:
  result:
    group: msrc:10852
    status: success
    total_time_seconds: 0.07997560501098633
    updated_image_count: 0
    updated_record_count: 0
id: b7e5957d885d411bb7068291a0317995
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10852
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:23.122749Z'
type: system.feeds.sync.group_completed
```
