### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#677]
```
details:
  result:
    group: npm
    status: success
    total_time_seconds: 1008.4908480644226
    updated_image_count: 0
    updated_record_count: 247000
id: 5b18f88b0dfd4c31853bcdd60f596d15
level: info
message: Feed group sync completed
resource:
  id: packages/npm
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T17:10:48.780243Z'
type: system.feeds.sync.group_completed
```
