### ISSUE TITLE
[ANCHORE] Feed sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#678]
```
details: {}
id: f28e21f60099468a8c43154f3badf2b8
level: info
message: Feed sync completed
resource:
  id: packages
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T17:10:48.872632Z'
type: system.feeds.sync.feed_completed
```
