### ISSUE TITLE
[ANCHORE] Feeds sync task completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#679]
```
details:
  sync_feed_types:
  - vulnerabilities
  - packages
  - nvdv2
  - vulndb
  - microsoft
  - github
id: b232bca073ef41eb9b3f75b7e84576fc
level: info
message: Feeds sync task completed
resource:
  id: null
  type: feeds
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T17:10:48.934267Z'
type: system.feeds.sync.completed
```
