### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#68]
```
details: {}
id: 66252e8beab34127af4967af3a2b5b3f
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11454
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:23.186559Z'
type: system.feeds.sync.group_started
```
