### ISSUE TITLE
[ANCHORE] Service down

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#682]
```
details:
  cause: no heartbeat from service in (300) seconds
  host_id: anchore-engine-anchore-engine-analyzer-b96d77666-7dddk
  service_name: analyzer
id: 50459829a630442bae499f58f0ae64b7
level: error
message: Service down
resource:
  id: http://anchore-engine-anchore-engine-analyzer:8084
  type: service
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-catalog:8082
  hostid: anchore-engine-anchore-engine-catalog-77849fbd77-gbknh
  request_id: null
  servicename: catalog
timestamp: '2020-05-19T17:34:01.752844Z'
type: system.service.state_transition.down
```
