### ISSUE TITLE
[ANCHORE] Service orphaned

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#688]
```
details:
  cause: no heartbeat from service in (3600) seconds
  host_id: anchore-engine-anchore-engine-analyzer-b96d77666-7dddk
  service_name: analyzer
id: 8ec721a3ff3c4a4d846a00a0b9304312
level: error
message: Service orphaned
resource:
  id: http://anchore-engine-anchore-engine-analyzer:8084
  type: service
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-catalog:8082
  hostid: anchore-engine-anchore-engine-catalog-77849fbd77-gbknh
  request_id: null
  servicename: catalog
timestamp: '2020-05-19T18:28:57.427869Z'
type: system.service.state_transition.orphaned
```
