### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#69]
```
details:
  result:
    group: msrc:11454
    status: success
    total_time_seconds: 0.06786322593688965
    updated_image_count: 0
    updated_record_count: 0
id: a115016b1c7c409f8a3965aee2d44aff
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11454
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:23.328942Z'
type: system.feeds.sync.group_completed
```
