### ISSUE TITLE
[ANCHORE] Feeds sync task started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#690]
```
details:
  sync_feed_types:
  - vulnerabilities
  - packages
  - nvdv2
  - vulndb
  - microsoft
  - github
id: a4d71b6f32254f3989d386d00336e2f6
level: info
message: Feeds sync task started
resource:
  id: null
  type: feeds
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:01.417375Z'
type: system.feeds.sync.started
```
