### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#691]
```
details: {}
id: b26d0ad507334e80b86b729ececc27fb
level: info
message: Feed sync started
resource:
  id: vulnerabilities
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:01.641012Z'
type: system.feeds.sync.feed_started
```
