### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#692]
```
details: {}
id: fe118f5e742942e3b9164652b20db624
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:01.703573Z'
type: system.feeds.sync.group_started
```
