### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#693]
```
details:
  result:
    group: alpine:3.10
    status: success
    total_time_seconds: 0.5918619632720947
    updated_image_count: 0
    updated_record_count: 0
id: 396f3d5286304578a39f6db2a53f15fd
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:02.374930Z'
type: system.feeds.sync.group_completed
```
