### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#695]
```
details:
  result:
    group: alpine:3.4
    status: success
    total_time_seconds: 0.10066437721252441
    updated_image_count: 0
    updated_record_count: 0
id: adcc7bb145d74777a4a3f26750e5530b
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.4
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:02.606007Z'
type: system.feeds.sync.group_completed
```
