### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#699]
```
details:
  result:
    group: alpine:3.5
    status: success
    total_time_seconds: 0.0808873176574707
    updated_image_count: 0
    updated_record_count: 0
id: 8da15b431c8b432aa4dfd0fa1631b26e
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:03.039776Z'
type: system.feeds.sync.group_completed
```
