### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#7]
```
details:
  result:
    group: msrc:10788
    status: success
    total_time_seconds: 0.07204866409301758
    updated_image_count: 0
    updated_record_count: 0
id: 3d47e39745fa4124a37b3619abf2ee4e
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10788
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:14.181456Z'
type: system.feeds.sync.group_completed
```
