### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#70]
```
details: {}
id: 87104f9902064c5ca7758bf219c97b10
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11453
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:23.388192Z'
type: system.feeds.sync.group_started
```
