### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#704]
```
details: {}
id: 221ded6e1d4f45cd883f60a7ddf2f320
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/centos:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:03.778359Z'
type: system.feeds.sync.group_started
```
