### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#705]
```
details:
  result:
    group: centos:5
    status: success
    total_time_seconds: 0.21542119979858398
    updated_image_count: 0
    updated_record_count: 0
id: bd7d4e353c33466a8b908ced6511c88e
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/centos:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:04.067296Z'
type: system.feeds.sync.group_completed
```
