### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#710]
```
details: {}
id: bba4679459054672ae8e18f90307c161
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:16.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:05.319091Z'
type: system.feeds.sync.group_started
```
