### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#711]
```
details:
  result:
    group: ubuntu:16.10
    status: success
    total_time_seconds: 0.5881125926971436
    updated_image_count: 0
    updated_record_count: 0
id: 62b9f74ae88841e9bcf5bd43c0a37fa0
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:16.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:05.983664Z'
type: system.feeds.sync.group_completed
```
