### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#712]
```
details: {}
id: 6fbee3f4529d4e3189b35cc736e66f1c
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:12.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:06.047547Z'
type: system.feeds.sync.group_started
```
