### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#715]
```
details:
  result:
    group: ubuntu:14.10
    status: success
    total_time_seconds: 0.3155477046966553
    updated_image_count: 0
    updated_record_count: 0
id: b6f9d0cea2ab4ecc90c35f7c3e469d2c
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:14.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:06.906701Z'
type: system.feeds.sync.group_completed
```
