### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#716]
```
details: {}
id: 6aae25f3d1bf4f2f8abc9a8473514dc3
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:14.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:06.989350Z'
type: system.feeds.sync.group_started
```
