### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#717]
```
details:
  result:
    group: ubuntu:14.04
    status: success
    total_time_seconds: 0.7601675987243652
    updated_image_count: 0
    updated_record_count: 0
id: d81d21fa81e547619922582172ff8268
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:14.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:07.824639Z'
type: system.feeds.sync.group_completed
```
