### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#719]
```
details:
  result:
    group: ubuntu:16.04
    status: success
    total_time_seconds: 0.649634838104248
    updated_image_count: 0
    updated_record_count: 2
id: 053f8a14ca33441e8acba86d74e08003
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:16.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:08.621158Z'
type: system.feeds.sync.group_completed
```
