### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#72]
```
details: {}
id: 880425fef8f645369ff1b7615761582d
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10855
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:23.605713Z'
type: system.feeds.sync.group_started
```
