### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#720]
```
details: {}
id: 28983b0051bf48e6a448f8d57255aee2
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:15.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:08.684253Z'
type: system.feeds.sync.group_started
```
