### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#723]
```
details:
  result:
    group: ubuntu:15.10
    status: success
    total_time_seconds: 0.32587766647338867
    updated_image_count: 0
    updated_record_count: 0
id: 1b37e3dc4f534487843cd1787913d2b7
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:15.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:09.519249Z'
type: system.feeds.sync.group_completed
```
