### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#724]
```
details: {}
id: bacc30e5e9464a3b8a2b00c83a8f4480
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:17.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:09.599190Z'
type: system.feeds.sync.group_started
```
