### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#725]
```
details:
  result:
    group: ubuntu:17.04
    status: success
    total_time_seconds: 0.38389039039611816
    updated_image_count: 0
    updated_record_count: 0
id: 6edd71638a4546de83f24fc811012df8
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:17.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:10.068426Z'
type: system.feeds.sync.group_completed
```
