### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#726]
```
details: {}
id: c64f067ffcd34410ac419f4524c68cd1
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:17.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:10.136191Z'
type: system.feeds.sync.group_started
```
