### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#727]
```
details:
  result:
    group: ubuntu:17.10
    status: success
    total_time_seconds: 0.3311934471130371
    updated_image_count: 0
    updated_record_count: 0
id: 8f8e295b0de64ab19bea17e0d610e92a
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:17.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:10.535570Z'
type: system.feeds.sync.group_completed
```
