### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#728]
```
details: {}
id: d18a183c18634dd2bc19090fd74b5b50
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/centos:6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:10.596999Z'
type: system.feeds.sync.group_started
```
