### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#729]
```
details:
  result:
    group: centos:6
    status: success
    total_time_seconds: 0.2820878028869629
    updated_image_count: 0
    updated_record_count: 0
id: 49448f34e9ed445eaaf0c902f9c1de03
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/centos:6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:10.949170Z'
type: system.feeds.sync.group_completed
```
