### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#73]
```
details:
  result:
    group: msrc:10855
    status: success
    total_time_seconds: 0.06855106353759766
    updated_image_count: 0
    updated_record_count: 0
id: d89536be329a4f9eace813333c974a23
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10855
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:23.747359Z'
type: system.feeds.sync.group_completed
```
