### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#731]
```
details:
  result:
    group: alpine:3.7
    status: success
    total_time_seconds: 0.17566680908203125
    updated_image_count: 0
    updated_record_count: 0
id: 968457d3515e49068454d85e9e9e859d
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:11.268688Z'
type: system.feeds.sync.group_completed
```
