### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#733]
```
details:
  result:
    group: debian:11
    status: success
    total_time_seconds: 1.3162529468536377
    updated_image_count: 0
    updated_record_count: 53
id: a14186ca2a5542279dbf44e1a52a114f
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/debian:11
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:12.754249Z'
type: system.feeds.sync.group_completed
```
