### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#735]
```
details:
  result:
    group: centos:8
    status: success
    total_time_seconds: 0.08695578575134277
    updated_image_count: 0
    updated_record_count: 0
id: ec0b547f56fe44f48d84fff9b57a0fbc
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/centos:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:13.011085Z'
type: system.feeds.sync.group_completed
```
