### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#737]
```
details:
  result:
    group: ubuntu:18.04
    status: success
    total_time_seconds: 0.5036087036132812
    updated_image_count: 0
    updated_record_count: 2
id: 3bb3e13544914159aa4a74747cc4f143
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:18.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:13.671402Z'
type: system.feeds.sync.group_completed
```
