### ISSUE TITLE
[ANCHORE] Feed sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#74]
```
details: {}
id: 4d20545338864ebf89707addf328aaf2
level: info
message: Feed sync completed
resource:
  id: microsoft
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:23.810017Z'
type: system.feeds.sync.feed_completed
```
