### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#740]
```
details: {}
id: 76b8955b4b4e4421b23eaca51ab0d2de
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/rhel:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:14.114698Z'
type: system.feeds.sync.group_started
```
