### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#741]
```
details:
  result:
    group: rhel:8
    status: success
    total_time_seconds: 0.4612586498260498
    updated_image_count: 0
    updated_record_count: 2
id: 62a1e3437ba8472baee6f32607c2721f
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/rhel:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:14.658412Z'
type: system.feeds.sync.group_completed
```
