### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#743]
```
details:
  result:
    group: debian:unstable
    status: success
    total_time_seconds: 0.9124934673309326
    updated_image_count: 0
    updated_record_count: 36
id: 2d7b6e6e6e2f47ea9a2d2ad9390b941f
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/debian:unstable
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:15.708802Z'
type: system.feeds.sync.group_completed
```
