### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#744]
```
details: {}
id: d883a48cb78949c0af74b0f6359ddccb
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/centos:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:15.778868Z'
type: system.feeds.sync.group_started
```
