### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#745]
```
details:
  result:
    group: centos:7
    status: success
    total_time_seconds: 0.2429342269897461
    updated_image_count: 0
    updated_record_count: 0
id: 0be8e07613684972af8b580f7a0c6787
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/centos:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:16.096169Z'
type: system.feeds.sync.group_completed
```
