### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#747]
```
details:
  result:
    group: debian:8
    status: success
    total_time_seconds: 0.7801625728607178
    updated_image_count: 0
    updated_record_count: 31
id: 5a6f8cb4a8984f289536d432c982d308
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/debian:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:17.025884Z'
type: system.feeds.sync.group_completed
```
