### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#748]
```
details: {}
id: 955acb09f3854befbf2dae81038e28cd
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/debian:10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:17.103056Z'
type: system.feeds.sync.group_started
```
