### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#749]
```
details:
  result:
    group: debian:10
    status: success
    total_time_seconds: 0.8662104606628418
    updated_image_count: 0
    updated_record_count: 37
id: 17a5fe133b5b462991907957f246dbb7
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/debian:10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:18.048105Z'
type: system.feeds.sync.group_completed
```
