### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#750]
```
details: {}
id: 7db51218758c4ee7a6695665415969d0
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/debian:9
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:18.117302Z'
type: system.feeds.sync.group_started
```
