### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#751]
```
details:
  result:
    group: debian:9
    status: success
    total_time_seconds: 0.7866611480712891
    updated_image_count: 0
    updated_record_count: 35
id: 1debf94c4cbd479ba02f85d362b442a2
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/debian:9
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:18.975478Z'
type: system.feeds.sync.group_completed
```
