### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#753]
```
details:
  result:
    group: ol:6
    status: success
    total_time_seconds: 0.18338632583618164
    updated_image_count: 0
    updated_record_count: 0
id: a5581346359344959df1aa9c1bb0133c
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ol:6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:19.309218Z'
type: system.feeds.sync.group_completed
```
