### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#754]
```
details: {}
id: 3fe20080ffdf4db69061d804f34e0b98
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ol:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:19.514797Z'
type: system.feeds.sync.group_started
```
