### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#755]
```
details:
  result:
    group: ol:5
    status: success
    total_time_seconds: 0.17800450325012207
    updated_image_count: 0
    updated_record_count: 0
id: 2db3e37b68e843acbc96360afa0377ad
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ol:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:19.775557Z'
type: system.feeds.sync.group_completed
```
