### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#757]
```
details:
  result:
    group: ol:8
    status: success
    total_time_seconds: 0.08120489120483398
    updated_image_count: 0
    updated_record_count: 0
id: 45add48bdb6242338d3d0c0210aea164
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ol:8
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:19.990969Z'
type: system.feeds.sync.group_completed
```
