### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#759]
```
details:
  result:
    group: rhel:5
    status: success
    total_time_seconds: 0.2761263847351074
    updated_image_count: 0
    updated_record_count: 0
id: b3403a751897422eb6179ac8de54f8fb
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/rhel:5
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:20.401535Z'
type: system.feeds.sync.group_completed
```
