### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#761]
```
details:
  result:
    group: ol:7
    status: success
    total_time_seconds: 0.17488670349121094
    updated_image_count: 0
    updated_record_count: 0
id: 624318652d1549548f4073a85db3ad2f
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ol:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:20.710617Z'
type: system.feeds.sync.group_completed
```
