### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#763]
```
details:
  result:
    group: rhel:7
    status: success
    total_time_seconds: 0.3330810070037842
    updated_image_count: 0
    updated_record_count: 2
id: acff58451c0c49fcad9ac2b05817e9ff
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/rhel:7
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:21.176758Z'
type: system.feeds.sync.group_completed
```
