### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#765]
```
details:
  result:
    group: ubuntu:18.10
    status: success
    total_time_seconds: 0.30679917335510254
    updated_image_count: 0
    updated_record_count: 0
id: c6608acfbbfd43dabf4a46f20c2c06d2
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:18.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:21.615131Z'
type: system.feeds.sync.group_completed
```
