### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#767]
```
details:
  result:
    group: rhel:6
    status: success
    total_time_seconds: 0.2077314853668213
    updated_image_count: 0
    updated_record_count: 0
id: cc3f6e59b55149bc8cffc9d4c760ad03
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/rhel:6
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:21.960149Z'
type: system.feeds.sync.group_completed
```
