### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#769]
```
details:
  result:
    group: ubuntu:19.10
    status: success
    total_time_seconds: 0.3204209804534912
    updated_image_count: 0
    updated_record_count: 2
id: 226c47ac54fe411898607c92da8a140e
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:19.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:22.427446Z'
type: system.feeds.sync.group_completed
```
