### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#77]
```
details:
  result:
    group: github:gem
    status: success
    total_time_seconds: 0.10206198692321777
    updated_image_count: 0
    updated_record_count: 0
id: 0c58af95325f431f9dad8a83e26c5685
level: info
message: Feed group sync completed
resource:
  id: github/github:gem
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:24.197658Z'
type: system.feeds.sync.group_completed
```
