### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#772]
```
details: {}
id: f64b3bda990c45f8835df0f05f2da0a5
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:19.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:22.803758Z'
type: system.feeds.sync.group_started
```
