### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#775]
```
details:
  result:
    group: ubuntu:13.04
    status: success
    total_time_seconds: 0.22914671897888184
    updated_image_count: 0
    updated_record_count: 0
id: 368b72c09d69419c9476498891b8292a
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:13.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:23.521628Z'
type: system.feeds.sync.group_completed
```
