### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#776]
```
details: {}
id: 44fa01f10e4348e2b8736412a7075a5b
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/ubuntu:20.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:23.583854Z'
type: system.feeds.sync.group_started
```
