### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#777]
```
details:
  result:
    group: ubuntu:20.04
    status: success
    total_time_seconds: 0.27592992782592773
    updated_image_count: 0
    updated_record_count: 2
id: 2ce9b325ab804df0880de09aea9248c2
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/ubuntu:20.04
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:23.935120Z'
type: system.feeds.sync.group_completed
```
