### ISSUE TITLE
[ANCHORE] Feed sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#778]
```
details: {}
id: 0919964bc76f43158b70faa988f2029a
level: info
message: Feed sync completed
resource:
  id: vulnerabilities
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:23.992836Z'
type: system.feeds.sync.feed_completed
```
