### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#779]
```
details: {}
id: b5f9c559b2d54977b047587dda257747
level: info
message: Feed sync started
resource:
  id: vulndb
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:24.053515Z'
type: system.feeds.sync.feed_started
```
