### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#78]
```
details: {}
id: 5487b4ad00b34cdcb3cc0011f48f8dba
level: info
message: Feed group sync started
resource:
  id: github/github:npm
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:24.265908Z'
type: system.feeds.sync.group_started
```
