### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#780]
```
details: {}
id: 3b91501958824e1cbf9c394c081e7f2d
level: info
message: Feed group sync started
resource:
  id: vulndb/vulndb:vulnerabilities
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T21:13:24.257826Z'
type: system.feeds.sync.group_started
```
