### ISSUE TITLE
[ANCHORE] Service removed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#781]
```
details:
  cause: no heartbeat from service in (86400) seconds
  host_id: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  service_name: policy_engine
id: 9d631a34bd464c57aed8a518989eaae7
level: error
message: Service removed
resource:
  id: http://anchore-engine-anchore-engine-policy:8087
  type: service
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-catalog:8082
  hostid: anchore-engine-anchore-engine-catalog-77849fbd77-gbknh
  request_id: null
  servicename: catalog
timestamp: '2020-05-19T22:03:47.851550Z'
type: system.service.removed
```
