### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#782]
```
details:
  result:
    group: vulndb:vulnerabilities
    status: success
    total_time_seconds: 4412.023881435394
    updated_image_count: 0
    updated_record_count: 223000
id: 46b94f748abd47e98e1b353cee0f226d
level: info
message: Feed group sync completed
resource:
  id: vulndb/vulndb:vulnerabilities
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:26:56.360361Z'
type: system.feeds.sync.group_completed
```
