### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#786]
```
details:
  result:
    group: nvdv2:cves
    status: success
    total_time_seconds: 0.6104536056518555
    updated_image_count: 0
    updated_record_count: 0
id: a4a9483ecf444d1c87324238e0aee106
level: info
message: Feed group sync completed
resource:
  id: nvdv2/nvdv2:cves
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:26:57.985920Z'
type: system.feeds.sync.group_completed
```
