### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#789]
```
details: {}
id: 4daab0a3beab4f85ba78f73b95cca4ca
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11644
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:26:58.311638Z'
type: system.feeds.sync.group_started
```
