### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#79]
```
details:
  result:
    group: github:npm
    status: success
    total_time_seconds: 0.09204387664794922
    updated_image_count: 0
    updated_record_count: 0
id: 483bb6958ef44611aa7ed2304c3bb453
level: info
message: Feed group sync completed
resource:
  id: github/github:npm
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:24.442688Z'
type: system.feeds.sync.group_completed
```
