### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#790]
```
details:
  result:
    group: msrc:11644
    status: success
    total_time_seconds: 0.13371777534484863
    updated_image_count: 0
    updated_record_count: 0
id: 1d1123c01b954050a623841caf40f787
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11644
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:26:58.526750Z'
type: system.feeds.sync.group_completed
```
