### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#791]
```
details: {}
id: c37b4f4c122644c0a99d6876163aa75c
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11713
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:26:58.589410Z'
type: system.feeds.sync.group_started
```
