### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#792]
```
details:
  result:
    group: msrc:11713
    status: success
    total_time_seconds: 0.14359235763549805
    updated_image_count: 0
    updated_record_count: 0
id: 43118de2e991498eb76ce7bdbac602d9
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11713
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:26:58.847842Z'
type: system.feeds.sync.group_completed
```
