### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#794]
```
details:
  result:
    group: msrc:11645
    status: success
    total_time_seconds: 0.10474729537963867
    updated_image_count: 0
    updated_record_count: 0
id: 22d023eabcf1407cac97ee0abe180050
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11645
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:26:59.151599Z'
type: system.feeds.sync.group_completed
```
