### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#795]
```
details: {}
id: 6cb1055f7d6b4289ab97b73a4042f3ec
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11647
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:26:59.220117Z'
type: system.feeds.sync.group_started
```
