### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#797]
```
details: {}
id: b14e4fa29dcd4bcfa55a3449e34fc7df
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:products
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:26:59.470271Z'
type: system.feeds.sync.group_started
```
