### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#798]
```
details:
  result:
    group: msrc:products
    status: success
    total_time_seconds: 0.06576132774353027
    updated_image_count: 0
    updated_record_count: 0
id: d9cbf96768d04827b16fbbd4824aeef4
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:products
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:26:59.616446Z'
type: system.feeds.sync.group_completed
```
