### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#799]
```
details: {}
id: 279914d181ea46f68f07d83a1fc8d8ce
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10951
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:26:59.676762Z'
type: system.feeds.sync.group_started
```
