### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#8]
```
details: {}
id: 9c74fed08a2f479b8899a350aa9dd1c6
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11499
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:14.244164Z'
type: system.feeds.sync.group_started
```
