### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#80]
```
details: {}
id: a2e982af325a40be9b0e1ef47d60ca23
level: info
message: Feed group sync started
resource:
  id: github/github:nuget
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:24.507014Z'
type: system.feeds.sync.group_started
```
