### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#800]
```
details:
  result:
    group: msrc:10951
    status: success
    total_time_seconds: 0.09401607513427734
    updated_image_count: 0
    updated_record_count: 0
id: 9340527963b6478394df05985e7a18dd
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10951
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:26:59.840228Z'
type: system.feeds.sync.group_completed
```
