### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#801]
```
details: {}
id: 4f8be75c46de41a0ab21f54648256e1e
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11715
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:26:59.902329Z'
type: system.feeds.sync.group_started
```
