### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#802]
```
details:
  result:
    group: msrc:11715
    status: success
    total_time_seconds: 0.09382152557373047
    updated_image_count: 0
    updated_record_count: 0
id: 696b23e94eaf4d289a2153a782d691c2
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11715
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:00.076352Z'
type: system.feeds.sync.group_completed
```
