### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#803]
```
details: {}
id: 5688a9250eb44b9aa3033f10ce75ffc8
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11572
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:00.148593Z'
type: system.feeds.sync.group_started
```
