### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#804]
```
details:
  result:
    group: msrc:11572
    status: success
    total_time_seconds: 0.09947896003723145
    updated_image_count: 0
    updated_record_count: 0
id: 4984660bf72247a8941a15028d15d489
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11572
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:00.331013Z'
type: system.feeds.sync.group_completed
```
