### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#806]
```
details:
  result:
    group: msrc:10543
    status: success
    total_time_seconds: 0.21761488914489746
    updated_image_count: 0
    updated_record_count: 0
id: c22b5f73456b4afdb7bb37a92ad6cc10
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10543
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:00.686837Z'
type: system.feeds.sync.group_completed
```
