### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#809]
```
details: {}
id: d137060d0d284644867774da351f2c23
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10735
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:01.016687Z'
type: system.feeds.sync.group_started
```
