### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#81]
```
details:
  result:
    group: github:nuget
    status: success
    total_time_seconds: 0.301332950592041
    updated_image_count: 0
    updated_record_count: 0
id: fa84c61271d447ba9fc3cebad6db99ee
level: info
message: Feed group sync completed
resource:
  id: github/github:nuget
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:24.885026Z'
type: system.feeds.sync.group_completed
```
