### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#810]
```
details:
  result:
    group: msrc:10735
    status: success
    total_time_seconds: 0.2230062484741211
    updated_image_count: 0
    updated_record_count: 0
id: 887a391c64544458a2cacb53f119585c
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10735
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:01.322057Z'
type: system.feeds.sync.group_completed
```
