### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#811]
```
details: {}
id: fbd7675cdfc3474fa33f2f2d88936e08
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11563
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:01.384086Z'
type: system.feeds.sync.group_started
```
