### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#812]
```
details:
  result:
    group: msrc:11563
    status: success
    total_time_seconds: 0.09394216537475586
    updated_image_count: 0
    updated_record_count: 0
id: f1d052a53e4844fe8545f0ed0f5a383b
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11563
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:01.565147Z'
type: system.feeds.sync.group_completed
```
