### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#814]
```
details:
  result:
    group: msrc:10853
    status: success
    total_time_seconds: 0.20970988273620605
    updated_image_count: 0
    updated_record_count: 0
id: d3a569fe7c624bc5837302b9602da085
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10853
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:01.917013Z'
type: system.feeds.sync.group_completed
```
