### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#815]
```
details: {}
id: 5d5d3231427a47b1a19dfa4cda191e74
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11714
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:01.988292Z'
type: system.feeds.sync.group_started
```
