### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#816]
```
details:
  result:
    group: msrc:11714
    status: success
    total_time_seconds: 0.09661221504211426
    updated_image_count: 0
    updated_record_count: 0
id: a5fde33dd282468287daaa3790361385
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11714
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:02.169612Z'
type: system.feeds.sync.group_completed
```
