### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#818]
```
details:
  result:
    group: msrc:10379
    status: success
    total_time_seconds: 0.2180323600769043
    updated_image_count: 0
    updated_record_count: 0
id: 3ac63ee5f5d147c2a416c100bbf8f95b
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10379
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:02.528250Z'
type: system.feeds.sync.group_completed
```
