### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#819]
```
details: {}
id: 5684ce62f1f8432e9bfe5dff6a5dd264
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10729
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:02.593766Z'
type: system.feeds.sync.group_started
```
