### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#821]
```
details: {}
id: e0ec5c85a5584b1dbfc70cf9b0f4b366
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10816
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:02.974891Z'
type: system.feeds.sync.group_started
```
