### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#822]
```
details:
  result:
    group: msrc:10816
    status: success
    total_time_seconds: 0.20958590507507324
    updated_image_count: 0
    updated_record_count: 0
id: 86d1e1199d5d4eeebe824ec969335622
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10816
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:03.256488Z'
type: system.feeds.sync.group_completed
```
