### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#824]
```
details:
  result:
    group: msrc:10952
    status: success
    total_time_seconds: 0.1000986099243164
    updated_image_count: 0
    updated_record_count: 0
id: 930fe87ce2c64358bde6981690065c1c
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10952
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:03.491000Z'
type: system.feeds.sync.group_completed
```
