### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#825]
```
details: {}
id: f9f97750ca63498b8311ed3b180679d7
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11569
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:03.553073Z'
type: system.feeds.sync.group_started
```
