### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#828]
```
details:
  result:
    group: msrc:11712
    status: success
    total_time_seconds: 0.09337806701660156
    updated_image_count: 0
    updated_record_count: 0
id: 7589fd5a44fd4fc0b6dc142ac5f34cd1
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11712
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:03.990585Z'
type: system.feeds.sync.group_completed
```
