### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#83]
```
details:
  result:
    group: github:python
    status: success
    total_time_seconds: 0.08147501945495605
    updated_image_count: 0
    updated_record_count: 0
id: 3b62ca12c6df423588b1c3272e4d6520
level: info
message: Feed group sync completed
resource:
  id: github/github:python
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:25.123771Z'
type: system.feeds.sync.group_completed
```
