### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#832]
```
details:
  result:
    group: msrc:10852
    status: success
    total_time_seconds: 0.2621033191680908
    updated_image_count: 0
    updated_record_count: 0
id: 5416a62e9305445c89f11ef1033dace1
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10852
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:04.640371Z'
type: system.feeds.sync.group_completed
```
