### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#833]
```
details: {}
id: 8ef349e6082d4a13a802b03d31542ed7
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11454
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:04.702452Z'
type: system.feeds.sync.group_started
```
