### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#835]
```
details: {}
id: 66b6d7751c0e4e17b9d99ccbd9655b9e
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11453
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:05.183299Z'
type: system.feeds.sync.group_started
```
