### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#836]
```
details:
  result:
    group: msrc:11453
    status: success
    total_time_seconds: 0.2401106357574463
    updated_image_count: 0
    updated_record_count: 0
id: 8e9504c4803549d6a9a6018da6024144
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11453
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:05.535778Z'
type: system.feeds.sync.group_completed
```
