### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#837]
```
details: {}
id: 748ac5a2dd3a462dad2af35bbc71a792
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10855
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:05.601026Z'
type: system.feeds.sync.group_started
```
