### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#838]
```
details:
  result:
    group: msrc:10855
    status: success
    total_time_seconds: 0.29772472381591797
    updated_image_count: 0
    updated_record_count: 0
id: 01a6ac6c335b44bd983f5b18659924fc
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10855
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:05.974592Z'
type: system.feeds.sync.group_completed
```
