### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#840]
```
details:
  result:
    group: msrc:10788
    status: success
    total_time_seconds: 0.09842967987060547
    updated_image_count: 0
    updated_record_count: 0
id: 5b793fe65c744c5a93b3fff22e61cac6
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10788
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:06.229672Z'
type: system.feeds.sync.group_completed
```
