### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#842]
```
details:
  result:
    group: msrc:11499
    status: success
    total_time_seconds: 0.09170699119567871
    updated_image_count: 0
    updated_record_count: 0
id: bbe8a01f99d24baa99629b995ffed6ef
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11499
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:06.466196Z'
type: system.feeds.sync.group_completed
```
