### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#843]
```
details: {}
id: 0c8fd51c44d1423bb6cdd43240b51e3f
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11498
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:06.530637Z'
type: system.feeds.sync.group_started
```
