### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#844]
```
details:
  result:
    group: msrc:11498
    status: success
    total_time_seconds: 0.22740459442138672
    updated_image_count: 0
    updated_record_count: 0
id: 6af134f650894f29abc5f823476e4b7a
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11498
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:06.832466Z'
type: system.feeds.sync.group_completed
```
