### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#848]
```
details:
  result:
    group: msrc:11570
    status: success
    total_time_seconds: 0.21892285346984863
    updated_image_count: 0
    updated_record_count: 0
id: bd28fa9e907f41a2af33e80739779f64
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11570
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:07.448956Z'
type: system.feeds.sync.group_completed
```
