### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#849]
```
details: {}
id: 5d71be2712a543c0b6d954fecc2c05bf
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11583
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:07.510074Z'
type: system.feeds.sync.group_started
```
