### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#85]
```
details:
  result:
    group: github:java
    status: success
    total_time_seconds: 0.07135701179504395
    updated_image_count: 0
    updated_record_count: 0
id: 8b12a104bf0145869cacc7330fba4b5b
level: info
message: Feed group sync completed
resource:
  id: github/github:java
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:25.329998Z'
type: system.feeds.sync.group_completed
```
