### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#850]
```
details:
  result:
    group: msrc:11583
    status: success
    total_time_seconds: 0.09574675559997559
    updated_image_count: 0
    updated_record_count: 0
id: 7d4f375dd6fe4b29b465196a5b0deb51
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11583
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:07.683716Z'
type: system.feeds.sync.group_completed
```
