### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#851]
```
details: {}
id: 49b73c02032343b9b4f5405cb82c2266
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11466
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:07.744738Z'
type: system.feeds.sync.group_started
```
