### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#852]
```
details:
  result:
    group: msrc:11466
    status: success
    total_time_seconds: 0.09343743324279785
    updated_image_count: 0
    updated_record_count: 0
id: e6dd6c010adb476fbcdd5cc2800985ea
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11466
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:07.909487Z'
type: system.feeds.sync.group_completed
```
