### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#853]
```
details: {}
id: 33d1a1e7b1204d46b3842903d264b8d8
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:11646
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:07.976916Z'
type: system.feeds.sync.group_started
```
