### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#854]
```
details:
  result:
    group: msrc:11646
    status: success
    total_time_seconds: 0.09363818168640137
    updated_image_count: 0
    updated_record_count: 0
id: 238b30184a034acab83226728c6f107b
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11646
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:08.141455Z'
type: system.feeds.sync.group_completed
```
