### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#855]
```
details: {}
id: 17a8be125c304a40aa0e5b4207991a03
level: info
message: Feed group sync started
resource:
  id: microsoft/msrc:10789
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:08.200096Z'
type: system.feeds.sync.group_started
```
