### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#856]
```
details:
  result:
    group: msrc:10789
    status: success
    total_time_seconds: 0.08944392204284668
    updated_image_count: 0
    updated_record_count: 0
id: 29cce92ae42c4d4481b8e32c60313eb7
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:10789
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:08.358671Z'
type: system.feeds.sync.group_completed
```
