### ISSUE TITLE
[ANCHORE] Feed sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#857]
```
details: {}
id: 58c0a3843b0f45f58a182404c27e76ac
level: info
message: Feed sync completed
resource:
  id: microsoft
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:08.415105Z'
type: system.feeds.sync.feed_completed
```
