### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#858]
```
details: {}
id: 51e6dd1089e24ec1ba8f01f1b728f65b
level: info
message: Feed sync started
resource:
  id: github
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:08.477787Z'
type: system.feeds.sync.feed_started
```
