### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#859]
```
details: {}
id: 81bf3c2a4fce456083eac9aa73037dba
level: info
message: Feed group sync started
resource:
  id: github/github:nuget
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:08.664632Z'
type: system.feeds.sync.group_started
```
