### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#860]
```
details:
  result:
    group: github:nuget
    status: success
    total_time_seconds: 0.10562682151794434
    updated_image_count: 0
    updated_record_count: 0
id: c0856521974e4205bc865dff54fa0ed7
level: info
message: Feed group sync completed
resource:
  id: github/github:nuget
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:08.846500Z'
type: system.feeds.sync.group_completed
```
