### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#861]
```
details: {}
id: f2c555fc9bd749e2bb2fe6355c8660c0
level: info
message: Feed group sync started
resource:
  id: github/github:python
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:08.910181Z'
type: system.feeds.sync.group_started
```
