### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#862]
```
details:
  result:
    group: github:python
    status: success
    total_time_seconds: 0.15698814392089844
    updated_image_count: 0
    updated_record_count: 1
id: ad16a730cea44ce5b4a70d593e773fbb
level: info
message: Feed group sync completed
resource:
  id: github/github:python
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:09.161362Z'
type: system.feeds.sync.group_completed
```
