### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#863]
```
details: {}
id: ccc07ad79d0c4a76ba6de1e45156f6bb
level: info
message: Feed group sync started
resource:
  id: github/github:java
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:09.240495Z'
type: system.feeds.sync.group_started
```
