### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#864]
```
details:
  result:
    group: github:java
    status: success
    total_time_seconds: 0.0999445915222168
    updated_image_count: 0
    updated_record_count: 0
id: 5c77883f3b234b5892e4b25de72a064e
level: info
message: Feed group sync completed
resource:
  id: github/github:java
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:09.417117Z'
type: system.feeds.sync.group_completed
```
