### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#866]
```
details:
  result:
    group: github:composer
    status: success
    total_time_seconds: 0.09303474426269531
    updated_image_count: 0
    updated_record_count: 0
id: 52bf5f24efb44d02909c9d976501e558
level: info
message: Feed group sync completed
resource:
  id: github/github:composer
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:09.663685Z'
type: system.feeds.sync.group_completed
```
