### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#868]
```
details:
  result:
    group: github:gem
    status: success
    total_time_seconds: 0.09221434593200684
    updated_image_count: 0
    updated_record_count: 0
id: b6a7b27b412c4226a40e0a3030d76ee8
level: info
message: Feed group sync completed
resource:
  id: github/github:gem
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:09.888422Z'
type: system.feeds.sync.group_completed
```
