### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#869]
```
details: {}
id: 1f8e4553937a41dca096612b55ffe291
level: info
message: Feed group sync started
resource:
  id: github/github:npm
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:09.950061Z'
type: system.feeds.sync.group_started
```
