### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#87]
```
details:
  result:
    group: github:composer
    status: success
    total_time_seconds: 0.08183741569519043
    updated_image_count: 0
    updated_record_count: 0
id: c5d15e91b2e3456c9d8ddf09ba522ff1
level: info
message: Feed group sync completed
resource:
  id: github/github:composer
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:25.581547Z'
type: system.feeds.sync.group_completed
```
