### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#870]
```
details:
  result:
    group: github:npm
    status: success
    total_time_seconds: 0.09488272666931152
    updated_image_count: 0
    updated_record_count: 0
id: bef3105c0e884db1a4d27b3622d61f01
level: info
message: Feed group sync completed
resource:
  id: github/github:npm
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:10.120022Z'
type: system.feeds.sync.group_completed
```
