### ISSUE TITLE
[ANCHORE] Feed sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#871]
```
details: {}
id: 07b685bb7aac43aca30b2258ad422ae0
level: info
message: Feed sync completed
resource:
  id: github
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:10.179389Z'
type: system.feeds.sync.feed_completed
```
