### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#874]
```
details:
  result:
    group: gem
    status: success
    total_time_seconds: 1.3483459949493408
    updated_image_count: 0
    updated_record_count: 258
id: 40426e105ea84a1f956fa0a5d14bbe06
level: info
message: Feed group sync completed
resource:
  id: packages/gem
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:11.918795Z'
type: system.feeds.sync.group_completed
```
