### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#875]
```
details: {}
id: 8761d76fc3304f9baf42d777a192334d
level: info
message: Feed group sync started
resource:
  id: packages/npm
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-19T22:27:12.005727Z'
type: system.feeds.sync.group_started
```
