### ISSUE TITLE
[ANCHORE] Feed sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#88]
```
details: {}
id: 45a6d29708c5498084bc086ce006b05a
level: info
message: Feed sync completed
resource:
  id: github
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:25.659406Z'
type: system.feeds.sync.feed_completed
```
