### ISSUE TITLE
[ANCHORE] Feeds sync task completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#89]
```
details:
  sync_feed_types:
  - microsoft
  - github
id: 5ca37eb8d5a34f08892e4cf5a5acba95
level: info
message: Feeds sync task completed
resource:
  id: null
  type: feeds
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:25.727728Z'
type: system.feeds.sync.completed
```
