### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#9]
```
details:
  result:
    group: msrc:11499
    status: success
    total_time_seconds: 0.07944154739379883
    updated_image_count: 0
    updated_record_count: 0
id: 984c078b13a842abb45d366c30c6a339
level: info
message: Feed group sync completed
resource:
  id: microsoft/msrc:11499
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-2478f
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T19:34:14.401769Z'
type: system.feeds.sync.group_completed
```
