### ISSUE TITLE
[ANCHORE] Feeds sync task started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#91]
```
details:
  sync_feed_types:
  - vulnerabilities
  - packages
  - nvdv2
  - vulndb
  - microsoft
  - github
id: 82451c766d674cbda6287e46533fe500
level: info
message: Feeds sync task started
resource:
  id: null
  type: feeds
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:03:57.399345Z'
type: system.feeds.sync.started
```
