### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#92]
```
details: {}
id: c94479c8a960413d8f4610c28a92983d
level: info
message: Feed sync started
resource:
  id: vulnerabilities
  type: feed
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:03:57.789857Z'
type: system.feeds.sync.feed_started
```
