### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#93]
```
details: {}
id: f8c504adc8dd4f768a99386e7e0f2fdf
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:03:57.858688Z'
type: system.feeds.sync.group_started
```
