### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#94]
```
details:
  result:
    group: alpine:3.10
    status: success
    total_time_seconds: 38.97748804092407
    updated_image_count: 0
    updated_record_count: 1723
id: 2df8db93e55341d29db619567e32ebde
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.10
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:04:36.926692Z'
type: system.feeds.sync.group_completed
```
