### ISSUE TITLE
[ANCHORE] Feed group sync started

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#95]
```
details: {}
id: 058b523c0cb94de68db38b5ac6021bb5
level: info
message: Feed group sync started
resource:
  id: vulnerabilities/alpine:3.11
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:04:37.012501Z'
type: system.feeds.sync.group_started
```
