### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#96]
```
details:
  result:
    group: alpine:3.11
    status: success
    total_time_seconds: 42.95177102088928
    updated_image_count: 0
    updated_record_count: 1904
id: 6af78d7190de45eba7aa06e671c40080
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.11
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:05:20.044055Z'
type: system.feeds.sync.group_completed
```
