### ISSUE TITLE
[ANCHORE] Feed group sync completed

### ISSUE THREAD

**Issue by found-it** [found-it/todoapi#98]
```
details:
  result:
    group: alpine:3.3
    status: success
    total_time_seconds: 9.641520738601685
    updated_image_count: 0
    updated_record_count: 457
id: 7b97f13346d44f069d996bcd719f621f
level: info
message: Feed group sync completed
resource:
  id: vulnerabilities/alpine:3.3
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-engine-anchore-engine-policy:8087
  hostid: anchore-engine-anchore-engine-policy-6f69f7b584-hwc6s
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-18T22:05:29.850526Z'
type: system.feeds.sync.group_completed
```
